import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ta' | 'ml' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    home: 'Home',
    dashboard: 'Dashboard',
    voiceAssistant: 'Voice Assistant',
    imageAnalysis: 'Image Analysis',
    cropAdvisory: 'Crop Advisory',
    weather: 'Weather',
    soilHealth: 'Soil Health',
    governmentSchemes: 'Government Schemes',
    diseaseManagement: 'Disease Management',
    cultivationGuide: 'Cultivation Guide',

    // Common
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',

    // Home Page
    welcomeTitle: 'AI-Based Agricultural Advisory System',
    welcomeSubtitle: 'Empowering Farmers in Tamil Nadu & Kerala',
    selectLanguage: 'Select Language',
    getStarted: 'Get Started',

    // Features
    voiceSupport: 'Voice Support',
    voiceSupportDesc: 'Ask questions using your voice in your preferred language',
    diseaseDetection: 'Disease Detection',
    diseaseDetectionDesc: 'Upload crop images for AI-powered disease analysis',
    expertAdvice: 'Expert Advice',
    expertAdviceDesc: 'Get personalized cultivation and crop management tips',
    weatherInsights: 'Weather Insights',
    weatherInsightsDesc: 'Real-time weather data and agricultural forecasts for better planning',
    soilHealthFeature: 'Soil Health',
    soilHealthFeatureDesc: 'Comprehensive soil analysis and improvement recommendations',
    governmentSchemesFeature: 'Government Schemes',
    governmentSchemesFeatureDesc: 'Access latest subsidies and support schemes for farmers',
    farmersHelped: 'Farmers Helped',
    accuracyRate: 'Accuracy Rate',
    supportAvailable: 'Support Available',
    comprehensiveAgriSolutions: 'Comprehensive Agricultural Solutions',
    everythingInOnePlace: 'Everything you need to make informed farming decisions, all in one place',
    joinSmartFarmers: 'Join Thousands of Smart Farmers',
    startJourneyDesc: 'Start your journey towards data-driven farming with AI-powered insights and expert guidance.',
    startFreeToday: 'Start Free Today',
    footerCopyright: '© 2024 KisanAi. Empowering farmers with AI technology.',
    moreServices: 'More Services',

    // Dashboard
    welcomeBack: 'Welcome back',
    farmer: 'Farmer',
    farmerName: 'Farmer Name',
    farmerProfile: 'Farmer Profile',
    farmSize: 'Farm Size',
    mainCrops: 'Main Crops',
    location: 'Location',
    notSpecified: 'Not specified',
    quickActions: 'Quick Actions',
    startNow: 'Start now',
    askQuestionsVoice: 'Ask questions using voice',
    uploadCropImages: 'Upload crop images for analysis',
    getCropRecommendations: 'Get crop recommendations',
    weatherForecastAlerts: 'Weather forecast & alerts',
    agriculturalDashboard: "Here's your agricultural dashboard for today",
    additionalServices: 'Additional Services',
    todayWeather: "Today's Weather",
    temperature: 'Temperature',
    humidity: 'Humidity',
    condition: 'Condition',
    rainfall: 'Rainfall',
    rainfallExpected: 'expected',
    partlyCloudy: 'Partly Cloudy',
    hazy: 'Hazy',
    noRainExpected: 'No rain expected',

    // Login
    signInAccount: 'Sign in to your account',
    welcomeBackAdvisor: 'Welcome back to your agricultural advisor',
    emailAddress: 'Email Address',
    password: 'Password',
    enterPassword: 'Enter your password',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    registerNow: 'Register now',

    // Register
    createAccount: 'Create your account',
    joinFarmers: 'Join thousands of smart farmers using AI technology',
    name: 'Name',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    confirmPassword: 'Confirm Password',
    state: 'State',
    selectState: 'Select your state',
    tamilNadu: 'Tamil Nadu',
    kerala: 'Kerala',
    mainCropsGrow: 'Main Crops You Grow',
    alreadyAccount: 'Already have an account?',
    loginNow: 'Login now',

    // Voice Assistant
    askQuestionsAboutFarming: 'Ask questions about farming using voice or text in your preferred language',
    speakOrType: 'Speak or Type Your Question',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    listening: 'Listening...',
    stopSpeaking: 'Stop Speaking',
    voiceOutput: 'Voice Output',
    typeQuestion: 'Type your question here...',
    send: 'Send',
    sampleQuestions: 'Sample Questions',
    processing: 'Processing...',
    welcomeMessage: 'Hello! I\'m your agricultural AI assistant. Ask me anything about farming, crops, diseases, or weather in Tamil Nadu and Kerala.',
    question1: 'Best crops for monsoon season?',
    question2: 'How to manage rice blast disease?',
    question3: 'Coconut fertilization schedule?',
    question4: 'Weather forecast for next week?',
    question5: 'Organic pest control methods?',
    question6: 'Government schemes for farmers?',

    // Image Analysis
    uploadCropImagesAnalysis: 'Upload crop images for AI-powered disease detection and analysis',
    dragDropImage: 'Drag and drop an image here',
    or: 'or',
    browseFiles: 'Browse Files',
    analyzeImage: 'Analyze Image',
    analyzing: 'Analyzing...',
    analysisResults: 'Analysis Results',
    diseaseStatus: 'Disease Status',
    detected: 'Detected',
    noDisease: 'No Disease Detected',
    confidence: 'Confidence',
    severity: 'Severity',
    affectedArea: 'Affected Area',
    recommendations: 'Recommendations',
    treatment: 'Treatment',
    prevention: 'Prevention',
    uploadNewImage: 'Upload New Image',
    additionalInformation: 'Additional Information',
    cropTypeOptional: 'Crop Type (Optional)',
    cropTypePlaceholder: 'e.g., Paddy, Coconut, Groundnut',
    symptomsNotesOptional: 'Symptoms/Notes (Optional)',
    symptomsPlaceholder: 'Describe any symptoms you have observed...',
    analyzingImage: 'Analyzing Image...',
    readyToAnalyze: 'Ready to Analyze',
    readyToAnalyzeDesc: 'Upload a clear image of your crop and click analyze to get AI-powered disease detection results.',
    tipsForBetterAnalysis: 'Tips for Better Analysis',
    clearImages: 'Clear Images',
    clearImagesDesc: 'Take clear, well-lit photos showing the affected areas clearly',
    closeUpShots: 'Close-up Shots',
    closeUpShotsDesc: 'Focus on specific symptoms like spots, discoloration, or damage',
    additionalInfo: 'Additional Info',
    additionalInfoDesc: 'Provide crop type and symptom details for more accurate results',
    changeImage: 'Change Image',
    confidenceScore: 'Confidence Score',
    healthStatus: 'Health Status',
    recommendedTreatment: 'Recommended Treatment',
    preventionTips: 'Prevention Tips',
    saveReport: 'Save Report',
    shareResults: 'Share Results',
    invalidFile: 'Invalid File',
    selectValidImage: 'Please select a valid image file.',
    noImageSelected: 'No Image Selected',
    selectImageToAnalyze: 'Please select an image to analyze.',
    analysisComplete: 'Analysis Complete',
    imageAnalyzedSuccess: 'Image has been successfully analyzed for diseases.',
    analysisFailed: 'Analysis Failed',
    unableToAnalyze: 'Unable to analyze image. Please try again.',

    // Weather
    realTimeWeatherData: 'Real-time weather data and agricultural forecasts for better farming decisions',
    getWeather: 'Get Weather',
    currentWeather: 'Current Weather',
    windSpeed: 'Wind Speed',
    visibility: 'Visibility',
    pressure: 'Pressure',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    forecast: 'Forecast',
    sevenDayForecast: '7-Day Forecast',
    today: 'Today',
    tomorrow: 'Tomorrow',
    viewFullForecast: 'View Full Forecast',
    todaysTip: "Today's Tip",
    learnMore: 'Learn More',
    uvIndex: 'UV Index',
    weatherAlerts: 'Weather Alerts',
    farmingAdvice: 'Farming Advice',
    enterLocation: 'Enter your location (e.g., Coimbatore, Tamil Nadu)',
    precipitation: 'Precipitation',
    high: 'High',
    low: 'Low',
    // Weather Conditions (from API)
    weatherClouds: 'Clouds',
    weatherClear: 'Clear',
    weatherRain: 'Rain',
    weatherDrizzle: 'Drizzle',
    weatherThunderstorm: 'Thunderstorm',
    weatherSnow: 'Snow',
    weatherMist: 'Mist',
    weatherHaze: 'Haze',
    weatherFog: 'Fog',
    weatherDust: 'Dust',
    weatherSmoke: 'Smoke',

    // Crop Advisory
    getCropAdvisoryRecommendations: 'Get crop advisory and personalized recommendations based on your conditions',
    selectCropType: 'Select Crop Type',
    soilType: 'Soil Type',
    season: 'Season',
    getRecommendations: 'Get Recommendations',
    fetching: 'Fetching...',
    advisory: 'Advisory',
    bestPractices: 'Best Practices',
    expectedYield: 'Expected Yield',
    waterRequirements: 'Water Requirements',
    fertilizerNeeds: 'Fertilizer Needs',
    commonPests: 'Common Pests',
    harvestTime: 'Harvest Time',
    farmDetails: 'Farm Details',
    locationDistrict: 'Location/District',
    locationPlaceholder: 'e.g., Coimbatore, Thrissur',
    selectSoilType: 'Select soil type',
    clayey: 'Clayey',
    sandy: 'Sandy',
    loamy: 'Loamy',
    redSoil: 'Red Soil',
    blackSoil: 'Black Soil',
    laterite: 'Laterite',
    alluvial: 'Alluvial',
    farmSizePlaceholder: 'e.g., 2 acres',
    preferredSeason: 'Preferred Season',
    selectSeason: 'Select season',
    kharif: 'Kharif (June-October)',
    rabi: 'Rabi (October-March)',
    summer: 'Summer (March-June)',
    perennialCrops: 'Perennial Crops',
    waterSource: 'Water Source',
    selectWaterSource: 'Select water source',
    rainFed: 'Rain-fed',
    irrigationSource: 'Irrigation',
    borewell: 'Borewell',
    canal: 'Canal',
    river: 'River',
    analyzingCrops: 'Analyzing...',
    currentConditions: 'Current Conditions',
    rainfallLabel: 'Rainfall:',
    temperatureLabel: 'Temperature:',
    humidityLabel: 'Humidity:',
    expected: 'Expected',
    cropRecommendations: 'Crop Recommendations',
    cropsFound: 'crops found',
    suitability: 'Suitability',
    soilTypes: 'Soil Types',
    demand: 'demand',
    risk: 'risk',
    advantages: 'Advantages',
    challenges: 'Challenges',
    readyForRecommendations: 'Ready for Recommendations',
    readyForRecommendationsDesc: 'Fill in your farm details on the left and click "Get Recommendations" to receive personalized crop suggestions.',

    // Soil Health
    soilTestingAndHealth: 'Soil testing and health monitoring for optimal crop growth',
    requestSoilTest: 'Request Soil Test',
    viewReports: 'View Reports',
    soilNutrients: 'Soil Nutrients',
    nitrogen: 'Nitrogen',
    phosphorus: 'Phosphorus',
    potassium: 'Potassium',
    organic: 'Organic',
    phLevel: 'pH Level',
    optimal: 'Optimal',

    // Soil Health Page
    soilHealthDesc: 'Analyze your soil composition and get personalized recommendations for better crop yields',
    soilTestData: 'Soil Test Data',
    sampleLocation: 'Sample Location',
    sampleLocationPlaceholder: 'e.g., Farm Block A, Coimbatore',
    sampleDate: 'Sample Date',
    depthCm: 'Depth (cm)',
    nutrientLevelsOptional: 'Nutrient Levels (Optional)',
    organicMatterPercent: 'Organic Matter (%)',
    nitrogenKgHa: 'Nitrogen (kg/ha)',
    phosphorusKgHa: 'Phosphorus (kg/ha)',
    potassiumKgHa: 'Potassium (kg/ha)',
    cropPlanned: 'Crop Planned',
    selectCropPlaceholder: 'Select crop',
    ricePaddy: 'Rice/Paddy',
    coconut: 'Coconut',
    groundnut: 'Groundnut',
    banana: 'Banana',
    pepper: 'Pepper',
    vegetables: 'Vegetables',
    millets: 'Millets',
    additionalNotes: 'Additional Notes',
    additionalNotesPlaceholder: 'Any observations about soil condition...',
    analyzingSoil: 'Analyzing...',
    analyzeSoil: 'Analyze Soil',
    overallSoilHealthScore: 'Overall Soil Health Score',
    excellent: 'Excellent',
    good: 'Good',
    needsImprovement: 'Needs Improvement',
    organicMatter: 'Organic Matter',
    nutrientRecommendations: 'Nutrient Recommendations',
    recommendedProducts: 'Recommended Products:',
    suitableCrops: 'Suitable Crops',
    improvementTips: 'Improvement Tips',
    downloadReport: 'Download Report',
    readyToAnalyzeSoil: 'Ready to Analyze',
    readyToAnalyzeSoilDesc: 'Enter your soil test data on the left or upload a lab report to get personalized recommendations for soil improvement.',
    dontHaveTestData: "Don't have test data?",
    generalRecommendationsNote: 'You can still get general recommendations by entering just your location!',
    missingInformation: 'Missing Information',
    enterSampleLocation: 'Please enter at least the sample location.',
    soilAnalysisComplete: 'Analysis Complete',
    soilAnalysisSuccess: 'Soil health analysis has been generated successfully.',

    // Government Schemes
    governmentSchemesForFarmers: 'Browse and apply for government schemes available for farmers',
    availableSchemes: 'Available Schemes',
    eligibility: 'Eligibility',
    benefits: 'Benefits',
    howToApply: 'How to Apply',
    applyNow: 'Apply Now',
    deadline: 'Deadline',
    
    // Scheme Titles
    scheme_pmksy: 'PM Krishi Sinchai Yojana',
    scheme_nfsm: 'National Food Security Mission',
    scheme_rkvy: 'Rashtriya Krishi Vikas Yojana',
    scheme_nhm: 'National Horticulture Mission',
    scheme_pmfme: 'PM Formalization of Micro Food Processing Enterprises',
    scheme_agri_mech_tn: 'Agricultural Mechanization Scheme (TN)',
    scheme_organic_kl: 'Organic Farming Promotion Scheme (KL)',
    scheme_pmkmdy: 'PM Kisan Maan Dhan Yojana',
    scheme_pmay: 'PM Awas Yojana (Gramin)',
    scheme_nlm: 'National Livestock Mission',
    scheme_pmmsy: 'PM Matsya Sampada Yojana',
    scheme_ami_tn: 'Agricultural Marketing Infrastructure (TN)',
    scheme_shc: 'Soil Health Card Scheme',
    scheme_wbci: 'Weather Based Crop Insurance Scheme',
    scheme_mif_tn: 'Micro Irrigation Fund (TN)',
    scheme_fwf_kl: 'Farmers Welfare Fund Board (KL)',
    scheme_atma: 'Agricultural Technology Management Agency',
    scheme_nmoop: 'National Mission on Oilseeds and Oil Palm',
    scheme_pmgkra: 'PM Garib Kalyan Rojgar Abhiyaan',
    scheme_isam: 'Integrated Scheme for Agricultural Marketing',
    scheme_pmsampada: 'PM Kisan Sampada Yojana',
    scheme_nmsa: 'National Mission for Sustainable Agriculture',
    scheme_pmkusum: 'Pradhan Mantri Kisan Urja Suraksha Yojana',
    scheme_pmabhy: 'PM Atmanirbhar Swasth Bharat Yojana',
    
    // Scheme Descriptions
    scheme_pmksy_desc: 'Promotes efficient irrigation and water conservation for farmers',
    scheme_nfsm_desc: 'Incentives for increasing production of rice, wheat, pulses, and coarse cereals',
    scheme_rkvy_desc: 'Funding for state-level agricultural development projects',
    scheme_nhm_desc: 'Support for horticulture crops, nurseries, and post-harvest management',
    scheme_pmfme_desc: 'Support for micro food processing units for upgradation and formalization',
    scheme_agri_mech_tn_desc: 'Subsidy for purchase of tractors, power tillers, and farm machinery',
    scheme_organic_kl_desc: 'Training and input support for organic farming in Kerala',
    scheme_pmkmdy_desc: 'Pension scheme for small and marginal farmers after 60 years of age',
    scheme_pmay_desc: 'Financial assistance for construction of houses in rural areas',
    scheme_nlm_desc: 'Support for livestock development, feed, and fodder',
    scheme_pmmsy_desc: 'Support for fisheries and aquaculture development',
    scheme_ami_tn_desc: 'Support for creation of market yards, cold storage, and processing units',
    scheme_shc_desc: 'Soil testing and health card distribution for better crop management',
    scheme_wbci_desc: 'Insurance coverage for crop loss due to adverse weather',
    scheme_mif_tn_desc: 'Loan and support for micro irrigation projects',
    scheme_fwf_kl_desc: 'Pension and welfare support for farmers in Kerala',
    scheme_atma_desc: 'Training and demonstration of new agricultural technologies',
    scheme_nmoop_desc: 'Support for oilseed and oil palm cultivation',
    scheme_pmgkra_desc: 'Wage employment and rural infrastructure for migrant workers',
    scheme_isam_desc: 'Support for marketing infrastructure and e-NAM integration',
    scheme_pmsampada_desc: 'Support for food processing and value addition',
    scheme_nmsa_desc: 'Training and support for climate-resilient agriculture',
    scheme_pmkusum_desc: 'Support for installation of solar pumps and grid-connected solar power plants',
    scheme_pmabhy_desc: 'Support for health and wellness centers in rural areas',

    // Disease Management
    identifyManageDiseases: 'Identify and manage crop diseases with expert guidance',
    diseaseManagementDesc: 'Identify, treat, and prevent crop diseases with expert guidance',
    searchDiseasesPlaceholder: 'Search diseases, symptoms, or crops...',
    commonDiseases: 'Common Diseases',
    symptoms: 'Symptoms',
    causes: 'Causes',
    control: 'Control',
    organicSolutions: 'Organic Solutions',
    chemicalTreatment: 'Chemical Treatment',
    highRisk: 'high risk',
    mediumRisk: 'medium risk',
    lowRisk: 'low risk',
    riceBlast: 'Rice Blast',
    riceBlastSymptoms: 'Brown spots with yellow halos on leaves',
    riceBlastTreatment: 'Apply Tricyclazole fungicide',
    riceBlastPrevention: 'Use resistant varieties, proper drainage',
    coconutRootWilt: 'Coconut Root Wilt',
    coconutRootWiltSymptoms: 'Yellowing of outer leaves, reduced nut production',
    coconutRootWiltTreatment: 'Root feeding with balanced fertilizer',
    coconutRootWiltPrevention: 'Proper drainage, organic matter addition',

    // Cultivation Guide
    stepByStepGuide: 'Step-by-step cultivation guides for various crops',
    cultivationGuideDesc: 'Step-by-step cultivation guides for major crops in Tamil Nadu and Kerala',
    selectCrop: 'Select Crop',
    paddy: 'Paddy',
    paddyRice: 'Paddy (Rice)',
    coconutCrop: 'Coconut',
    cultivationGuideTitle: 'Cultivation Guide',
    landPreparation: 'Land Preparation',
    landPreparationDesc: 'Plough field, level ground, prepare nursery beds',
    landPreparationDuration: '15 days',
    sowingTransplanting: 'Sowing/Transplanting',
    sowingTransplantingDesc: 'Sow seeds in nursery, transplant 30-day old seedlings',
    sowingTransplantingDuration: '30-35 days',
    vegetativeGrowth: 'Vegetative Growth',
    vegetativeGrowthDesc: 'Apply fertilizers, maintain water level, weed control',
    vegetativeGrowthDuration: '40-50 days',
    reproductivePhase: 'Reproductive Phase',
    reproductivePhaseDesc: 'Panicle initiation, flowering, grain formation',
    reproductivePhaseDuration: '30-35 days',
    maturation: 'Maturation',
    maturationDesc: 'Grain filling, field drying before harvest',
    maturationDuration: '30 days',
    siteSelection: 'Site Selection',
    siteSelectionDesc: 'Choose well-drained coastal or inland areas',
    initial: 'Initial',
    planting: 'Planting',
    plantingDesc: 'Plant quality seedlings with proper spacing (7.5m x 7.5m)',
    oneMonth: '1 month',
    youngPalmCare: 'Young Palm Care',
    youngPalmCareDesc: 'Regular watering, fertilization, pest management',
    threeToFiveYears: '3-5 years',
    bearingStage: 'Bearing Stage',
    bearingStageDesc: 'Regular harvesting every 45 days, continuous care',
    fivePlusYears: '5+ years',
    maintenance: 'Maintenance',
    maintenanceDesc: 'Pruning, fertilization, disease monitoring',
    ongoing: 'Ongoing',
    sowing: 'Sowing',
    irrigation: 'Irrigation',
    weeding: 'Weeding',
    harvesting: 'Harvesting',
    postHarvest: 'Post Harvest',
    duration: 'Duration',
    investment: 'Investment',
  },
  ta: {
    // Navigation - Tamil
    home: 'முகப்பு',
    dashboard: 'டாஷ்போர்டு',
    voiceAssistant: 'குரல் உதவியாளர்',
    imageAnalysis: 'படம் பகுப்பாய்வு',
    cropAdvisory: 'பயிர் ஆலோசனை',
    weather: 'வானிலை',
    soilHealth: 'மண் ஆரோக்கியம்',
    governmentSchemes: 'அரசு திட்டங்கள்',
    diseaseManagement: 'நோய் மேலாண்மை',
    cultivationGuide: 'சாகுபடி வழிகாட்டி',

    // Common
    login: 'உள்நுழை',
    register: 'பதிவு செய்',
    logout: 'வெளியேறு',
    submit: 'சமர்ப்பி',
    cancel: 'ரத்து செய்',
    save: 'சேமி',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    search: 'தேடு',

    // Home Page
    welcomeTitle: 'AI அடிப்படையிலான விவசாய ஆலோசனை அமைப்பு',
    welcomeSubtitle: 'தமிழ்நாடு & கேரள விவசாயிகளுக்கு அதிகாரம்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    getStarted: 'தொடங்குங்கள்',

    // Features
    voiceSupport: 'குரல் ஆதரவு',
    voiceSupportDesc: 'உங்கள் விரும்பிய மொழியில் குரல் மூலம் கேள்விகள் கேளுங்கள்',
    diseaseDetection: 'நோய் கண்டறிதல்',
    diseaseDetectionDesc: 'AI சக்தியால் நோய் பகுப்பாய்வுக்காக பயிர் படங்களை பதிவேற்றவும்',
    expertAdvice: 'நிபுணர் ஆலோசனை',
    expertAdviceDesc: 'தனிப்பயனாக்கப்பட்ட சாகுபடி மற்றும் பயிர் மேலாண்மை குறிப்புகளைப் பெறுங்கள்', weatherInsights: 'வானிலை நுழைவுகள்',
    weatherInsightsDesc: 'சிறந்த திட்டமிடலுக்கு நேரத்தில் வானிலை தரவு மற்றும் விவசாய முன்னறிவிப்புகள்',
    soilHealthFeature: 'மண் ஆரோக்கியம்',
    soilHealthFeatureDesc: 'விரிவான மண் பகுப்பாய்வு மற்றும் மேம்பாடு பரிந்துரைகள்',
    governmentSchemesFeature: 'அரசு திட்டங்கள்',
    governmentSchemesFeatureDesc: 'விவசாயிகளுக்கான செயலி துணைகள் மற்றும் ஆதரவு திட்டங்களை அணுகவும்',
    farmersHelped: 'விவசாயிகளுக்கு உதவி',
    accuracyRate: 'தீர்ப்பு விகிதம்',
    supportAvailable: 'ஆதரவு கிடைக்கும்',
    comprehensiveAgriSolutions: 'விரிவான விவசாய தீர்வுகள்',
    moreServices: 'மேலும் சேவைகள்',
    viewFullForecast: 'முழு முன்னறிவிப்பைக் காண்க',
    // Dashboard
    welcomeBack: 'வணக்கம்',
    farmer: 'விவசாயி',
    farmerName: 'விவசாயி பெயர்',
    farmerProfile: 'விவசாயி சுயவிவரம்',
    farmSize: 'பண்ணை அளவு',
    mainCrops: 'முக்கிய பயிர்கள்',
    location: 'இடம்',
    notSpecified: 'குறிப்பிடப்படவில்லை',
    quickActions: 'விரைவு செயல்கள்',
    startNow: 'இப்போது தொடங்குங்கள்',
    askQuestionsVoice: 'குரல் மூலம் கேள்விகள் கேளுங்கள்',
    uploadCropImages: 'பகுப்பாய்வுக்காக பயிர் படங்களை பதிவேற்றவும்',
    getCropRecommendations: 'பயிர் பரிந்துரைகளைப் பெறுங்கள்',
    weatherForecastAlerts: 'வானிலை முன்னறிவிப்பு & எச்சரிக்கைகள்',
    agriculturalDashboard: 'இன்றைய உங்கள் விவசாய டாஷ்போர்டு இதோ',
    additionalServices: 'கூடுதல் சேவைகள்',
    todayWeather: 'இன்றைய வானிலை',
    temperature: 'வெப்பநிலை',
    humidity: 'ஈரப்பதம்',
    condition: 'நிலை',
    rainfall: 'மழைப்பொழிவு',
    rainfallExpected: 'எதிர்பார்க்கப்படுகிறது',
    partlyCloudy: 'ஓரளவு மேகமூட்டம்',
    hazy: 'மூடுபனி',
    noRainExpected: 'மழை எதிர்பார்க்கப்படவில்லை',
    currentWeather: 'தற்போதைய வானிலை',
    windSpeed: 'காற்றின் வேகம்',
    visibility: 'தெரிவு நிலை',
    sevenDayForecast: '7 நாள் முன்னறிவிப்பு',
    getWeather: 'வானிலை பெறுக',
    realTimeWeatherData: 'சிறந்த விவசாய முடிவுகளுக்கான நிகழ்நேர வானிலை தரவு மற்றும் விவசாய முன்னறிவிப்புகள்',
    clouds: 'மேகங்கள்',
    sunny: 'வெயிலான',
    rainy: 'மழை',

    // Login
    signInAccount: 'உங்கள் கணக்கில் உள்நுழையவும்',
    welcomeBackAdvisor: 'உங்கள் விவசாய ஆலோசகரிடம் மீண்டும் வரவேற்கிறோம்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    enterPassword: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    noAccount: 'கணக்கு இல்லையா?',
    registerNow: 'இப்போது பதிவு செய்க',

    // Register
    createAccount: 'உங்கள் கணக்கை உருவாக்கவும்',
    joinFarmers: 'AI தொழில்நுட்பத்தைப் பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் சேரவும்',
    name: 'பெயர்',
    fullName: 'முழு பெயர்',
    phoneNumber: 'தொலைபேசி எண்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    state: 'மாநிலம்',
    selectState: 'உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    tamilNadu: 'தமிழ்நாடு',
    kerala: 'கேரளா',
    mainCropsGrow: 'நீங்கள் வளர்க்கும் முக்கிய பயிர்கள்',
    alreadyAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    loginNow: 'இப்போது உள்நுழையவும்',
    // Weather Conditions
    weatherClouds: 'மேகங்கள்',
    weatherClear: 'தெளிவான',
    weatherRain: 'மழை',
    weatherDrizzle: 'தூறல்',
    weatherThunderstorm: 'இடியுடன் மழை',
    weatherSnow: 'பனி',
    weatherMist: 'மூடுபனி',
    weatherHaze: 'புகை மூட்டம்',
    weatherFog: 'கடும் மூடுபனி',
    weatherDust: 'தூசி',
    weatherSmoke: 'புகை',

    // Weather
    uvIndex: 'UV குறியீடு',
    weatherAlerts: 'வானிலை எச்சரிக்கைகள்',
    farmingAdvice: 'விவசாய ஆலோசனை',
    enterLocation: 'உங்கள் இருப்பிடத்தை உள்ளிடவும் (உதா., கோயம்புத்தூர், தமிழ்நாடு)',
    precipitation: 'மழைப்பொழிவு',
    high: 'அதிக',
    low: 'குறைவு',

    // Voice Assistant
    askQuestionsAboutFarming: 'உங்கள் விரும்பிய மொழியில் குரல் அல்லது உரை மூலம் விவசாயம் பற்றிய கேள்விகள் கேளுங்கள்',
    speakOrType: 'உங்கள் கேள்வியைப் பேசவும் அல்லது தட்டச்சு செய்யவும்',
    startRecording: 'பதிவு செய்ய தொடங்கவும்',
    stopRecording: 'பதிவு நிறுத்தவும்',
    listening: 'கேட்கிறது...',
    stopSpeaking: 'பேசுவதை நிறுத்து',
    voiceOutput: 'குரல் வெளியீடு',
    typeQuestion: 'உங்கள் கேள்வியை இங்கே தட்டச்சு செய்யவும்...',
    send: 'அனுப்பு',
    sampleQuestions: 'மாதிரி கேள்விகள்',
    processing: 'செயலாக்குகிறது...',
    welcomeMessage: 'வணக்கம்! நான் உங்கள் விவசாய AI உதவியாளர். தமிழ்நாடு மற்றும் கேரளாவில் விவசாயம், பயிர்கள், நோய்கள் அல்லது வானிலை பற்றி எதையும் என்னிடம் கேளுங்கள்.',

    // Image Analysis
    uploadCropImagesAnalysis: 'AI சக்தியுடன் நோய் கண்டறிதல் மற்றும் பகுப்பாய்வுக்காக பயிர் படங்களை பதிவேற்றவும்',
    dragDropImage: 'ஒரு படத்தை இங்கே இழுத்து விடவும்',
    or: 'அல்லது',
    browseFiles: 'கோப்புகளை உலாவவும்',
    analyzeImage: 'படத்தை பகுப்பாய்வு செய்',
    analyzing: 'பகுப்பாய்வு செய்கிறது...',
    analysisResults: 'பகுப்பாய்வு முடிவுகள்',
    additionalInformation: 'கூடுதல் தகவல்',
    cropTypeOptional: 'பயிர் வகை (விருப்பத்தேர்வு)',
    cropTypePlaceholder: 'உதா., நெல், தேங்காய், வேர்க்கடலை',
    symptomsNotesOptional: 'அறிகுறிகள்/குறிப்புகள் (விருப்பத்தேர்வு)',
    symptomsPlaceholder: 'நீங்கள் கவனித்த அறிகுறிகளை விவரிக்கவும்...',
    analyzingImage: 'படத்தை பகுப்பாய்வு செய்கிறது...',
    readyToAnalyze: 'பகுப்பாய்வுக்கு தயார்',
    readyToAnalyzeDesc: 'உங்கள் பயிரின் தெளிவான படத்தை பதிவேற்றி AI சக்தியுடன் நோய் கண்டறிதல் முடிவுகளைப் பெற பகுப்பாய்வு செய்யுங்கள்.',
    tipsForBetterAnalysis: 'சிறந்த பகுப்பாய்வுக்கான குறிப்புகள்',
    clearImages: 'தெளிவான படங்கள்',
    clearImagesDesc: 'பாதிக்கப்பட்ட பகுதிகளை தெளிவாகக் காட்டும் நன்கு ஒளியூட்டப்பட்ட படங்களை எடுக்கவும்',
    closeUpShots: 'க்ளோஸ்-அப் ஷாட்கள்',
    closeUpShotsDesc: 'புள்ளிகள், நிறமாற்றம் அல்லது சேதம் போன்ற குறிப்பிட்ட அறிகுறிகளில் கவனம் செலுத்துங்கள்',
    additionalInfo: 'கூடுதல் தகவல்',
    additionalInfoDesc: 'மிகவும் துல்லியமான முடிவுகளுக்கு பயிர் வகை மற்றும் அறிகுறி விவரங்களை வழங்கவும்',
    changeImage: 'படத்தை மாற்று',
    confidenceScore: 'நம்பிக்கை மதிப்பெண்',
    healthStatus: 'ஆரோக்கிய நிலை',
    recommendedTreatment: 'பரிந்துரைக்கப்பட்ட சிகிச்சை',
    preventionTips: 'தடுப்பு குறிப்புகள்',
    saveReport: 'அறிக்கையை சேமி',
    shareResults: 'முடிவுகளைப் பகிர்',

    // Crop Advisory
    farmDetails: 'பண்ணை விவரங்கள்',
    locationDistrict: 'இடம்/மாவட்டம்',
    locationPlaceholder: 'உதா., கோயம்புத்தூர், திருச்சூர்',
    selectSoilType: 'மண் வகையைத் தேர்ந்தெடுக்கவும்',
    clayey: 'களிமண்',
    sandy: 'மணல்',
    loamy: 'வண்டல்',
    redSoil: 'செம்மண்',
    blackSoil: 'கருப்பு மண்',
    laterite: 'லேட்டரைட்',
    alluvial: 'வண்டல் மண்',
    farmSizePlaceholder: 'உதா., 2 ஏக்கர்',
    preferredSeason: 'விருப்பமான பருவம்',
    selectSeason: 'பருவத்தைத் தேர்ந்தெடுக்கவும்',
    kharif: 'கரீஃப் (ஜூன்-அக்டோபர்)',
    rabi: 'ரபி (அக்டோபர்-மார்ச்)',
    summer: 'கோடை (மார்ச்-ஜூன்)',
    perennialCrops: 'பலவருட பயிர்கள்',
    waterSource: 'நீர் ஆதாரம்',
    selectWaterSource: 'நீர் ஆதாரத்தைத் தேர்ந்தெடுக்கவும்',
    rainFed: 'மழை சார்ந்த',
    irrigationSource: 'பாசனம்',
    borewell: 'போர்வெல்',
    canal: 'கால்வாய்',
    river: 'ஆறு',
    analyzingCrops: 'பகுப்பாய்வு செய்கிறது...',
    currentConditions: 'தற்போதைய நிலைகள்',
    rainfallLabel: 'மழைப்பொழிவு:',
    temperatureLabel: 'வெப்பநிலை:',
    humidityLabel: 'ஈரப்பதம்:',
    expected: 'எதிர்பார்க்கப்படுகிறது',
    cropRecommendations: 'பயிர் பரிந்துரைகள்',
    cropsFound: 'பயிர்கள் கண்டறியப்பட்டன',
    suitability: 'பொருத்தம்',
    soilTypes: 'மண் வகைகள்',
    demand: 'தேவை',
    risk: 'ஆபத்து',
    advantages: 'நன்மைகள்',
    challenges: 'சவால்கள்',
    readyForRecommendations: 'பரிந்துரைகளுக்கு தயார்',
    readyForRecommendationsDesc: 'இடதுபுறத்தில் உங்கள் பண்ணை விவரங்களை நிரப்பி, தனிப்பயனாக்கப்பட்ட பயிர் பரிந்துரைகளைப் பெற "பரிந்துரைகளைப் பெறு" என்பதைக் கிளிக் செய்யவும்.',
    // Soil Health Page
    soilHealthDesc: 'சிறந்த பயிர் விளைச்சலுக்கு உங்கள் மண் கலவையை பகுப்பாய்வு செய்து தனிப்பயனாக்கப்பட்ட பரிந்துரைகளைப் பெறுங்கள்',
    soilTestData: 'மண் சோதனை தரவு',
    sampleLocation: 'மாதிரி இடம்',
    sampleLocationPlaceholder: 'உதா., பண்ணை பிளாக் A, கோயம்புத்தூர்',
    sampleDate: 'மாதிரி தேதி',
    depthCm: 'ஆழம் (செ.மீ)',
    nutrientLevelsOptional: 'ஊட்டச்சத்து அளவுகள் (விருப்பம்)',
    organicMatterPercent: 'கரிம பொருள் (%)',
    nitrogenKgHa: 'நைட்ரஜன் (கிலோ/ஹெக்டேர்)',
    phosphorusKgHa: 'பாஸ்பரஸ் (கிலோ/ஹெக்டேர்)',
    potassiumKgHa: 'பொட்டாசியம் (கிலோ/ஹெக்டேர்)',
    cropPlanned: 'திட்டமிடப்பட்ட பயிர்',
    selectCropPlaceholder: 'பயிரைத் தேர்ந்தெடுக்கவும்',
    ricePaddy: 'நெல்/அரிசி',
    coconut: 'தேங்காய்',
    groundnut: 'வேர்க்கடலை',
    banana: 'வாழை',
    pepper: 'மிளகு',
    vegetables: 'காய்கறிகள்',
    millets: 'சிறுதானியங்கள்',
    additionalNotes: 'கூடுதல் குறிப்புகள்',
    additionalNotesPlaceholder: 'மண் நிலை பற்றிய ஏதேனும் கவனிப்புகள்...',
    analyzingSoil: 'பகுப்பாய்வு செய்கிறது...',
    analyzeSoil: 'மண்ணை பகுப்பாய்வு செய்',
    overallSoilHealthScore: 'ஒட்டுமொத்த மண் ஆரோக்கிய மதிப்பெண்',
    excellent: 'சிறந்தது',
    good: 'நல்லது',
    needsImprovement: 'மேம்பாடு தேவை',
    organicMatter: 'கரிம பொருள்',
    nutrientRecommendations: 'ஊட்டச்சத்து பரிந்துரைகள்',
    recommendedProducts: 'பரிந்துரைக்கப்பட்ட தயாரிப்புகள்:',
    suitableCrops: 'பொருத்தமான பயிர்கள்',
    improvementTips: 'மேம்பாட்டு குறிப்புகள்',
    downloadReport: 'அறிக்கையைப் பதிவிறக்கு',
    readyToAnalyzeSoil: 'பகுப்பாய்வுக்கு தயார்',
    readyToAnalyzeSoilDesc: 'இடதுபுறத்தில் உங்கள் மண் சோதனை தரவை உள்ளிடவும் அல்லது மண் மேம்பாட்டிற்கான தனிப்பயனாக்கப்பட்ட பரிந்துரைகளைப் பெற ஆய்வக அறிக்கையைப் பதிவேற்றவும்.',
    dontHaveTestData: 'சோதனை தரவு இல்லையா?',
    generalRecommendationsNote: 'உங்கள் இருப்பிடத்தை மட்டும் உள்ளிட்டு பொதுவான பரிந்துரைகளைப் பெறலாம்!',
    missingInformation: 'தகவல் காணவில்லை',
    enterSampleLocation: 'குறைந்தபட்சம் மாதிரி இருப்பிடத்தை உள்ளிடவும்.',
    soilAnalysisComplete: 'பகுப்பாய்வு முடிந்தது',
    soilAnalysisSuccess: 'மண் ஆரோக்கிய பகுப்பாய்வு வெற்றிகரமாக உருவாக்கப்பட்டது.',

    // Disease Management Page
    diseaseManagementDesc: 'நிபுணர் வழிகாட்டுதலுடன் பயிர் நோய்களை அடையாளம் காணவும், சிகிச்சையளிக்கவும், தடுக்கவும்',
    searchDiseasesPlaceholder: 'நோய்கள், அறிகுறிகள் அல்லது பயிர்களைத் தேடுங்கள்...',
    symptoms: 'அறிகுறிகள்',
    treatment: 'சிகிச்சை',
    prevention: 'தடுப்பு',
    highRisk: 'அதிக ஆபத்து',
    mediumRisk: 'நடுத்தர ஆபத்து',
    lowRisk: 'குறைந்த ஆபத்து',
    riceBlast: 'நெல் கருகல் நோய்',
    riceBlastSymptoms: 'இலைகளில் மஞ்சள் வளையங்களுடன் பழுப்பு புள்ளிகள்',
    riceBlastTreatment: 'டிரைசைக்ளாசோல் பூஞ்சைக் கொல்லியைப் பயன்படுத்தவும்',
    riceBlastPrevention: 'எதிர்ப்புத் திறன் கொண்ட ரகங்களைப் பயன்படுத்தவும், சரியான வடிகால்',
    coconutRootWilt: 'தேங்காய் வேர் அழுகல்',
    coconutRootWiltSymptoms: 'வெளிப்புற இலைகள் மஞ்சளாதல், தேங்காய் உற்பத்தி குறைவு',
    coconutRootWiltTreatment: 'சமச்சீர் உரத்துடன் வேர் ஊட்டம்',
    coconutRootWiltPrevention: 'சரியான வடிகால், கரிமப் பொருள் சேர்த்தல்',

    // Cultivation Guide Page
    cultivationGuideDesc: 'தமிழ்நாடு மற்றும் கேரளாவில் முக்கிய பயிர்களுக்கான படிப்படியான சாகுபடி வழிகாட்டிகள்',
    paddy: 'நெல்',
    paddyRice: 'நெல் (அரிசி)',
    coconutCrop: 'தேங்காய்',
    cultivationGuideTitle: 'சாகுபடி வழிகாட்டி',
    landPreparation: 'நில தயாரிப்பு',
    landPreparationDesc: 'வயலை உழுதல், தரையை சமன் செய்தல், நாற்றங்கால் படுக்கைகளை தயாரித்தல்',
    landPreparationDuration: '15 நாட்கள்',
    sowingTransplanting: 'விதைப்பு/நடவு',
    sowingTransplantingDesc: 'நாற்றங்காலில் விதைகளை விதைக்கவும், 30 நாள் வயது நாற்றுகளை நடவும்',
    sowingTransplantingDuration: '30-35 நாட்கள்',
    vegetativeGrowth: 'தாவர வளர்ச்சி',
    vegetativeGrowthDesc: 'உரங்களைப் பயன்படுத்தவும், நீர் மட்டத்தை பராமரிக்கவும், களை கட்டுப்பாடு',
    vegetativeGrowthDuration: '40-50 நாட்கள்',
    reproductivePhase: 'இனப்பெருக்க கட்டம்',
    reproductivePhaseDesc: 'கதிர் உருவாக்கம், பூக்கள், தானிய உருவாக்கம்',
    reproductivePhaseDuration: '30-35 நாட்கள்',
    maturation: 'முதிர்ச்சி',
    maturationDesc: 'தானிய நிரப்புதல், அறுவடைக்கு முன் வயல் உலர்த்துதல்',
    maturationDuration: '30 நாட்கள்',
    siteSelection: 'இடத்தேர்வு',
    siteSelectionDesc: 'நன்கு வடிகால் கொண்ட கடலோர அல்லது உள்நாட்டு பகுதிகளைத் தேர்ந்தெடுக்கவும்',
    initial: 'ஆரம்பம்',
    planting: 'நடவு',
    plantingDesc: 'சரியான இடைவெளியுடன் தரமான நாற்றுகளை நடவும் (7.5மீ x 7.5மீ)',
    oneMonth: '1 மாதம்',
    youngPalmCare: 'இளம் தேங்காய் மர பராமரிப்பு',
    youngPalmCareDesc: 'தொடர்ச்சியான நீர்ப்பாசனம், உரமிடுதல், பூச்சி மேலாண்மை',
    threeToFiveYears: '3-5 ஆண்டுகள்',
    bearingStage: 'காய்க்கும் நிலை',
    bearingStageDesc: 'ஒவ்வொரு 45 நாட்களுக்கும் தொடர் அறுவடை, தொடர்ச்சியான பராமரிப்பு',
    fivePlusYears: '5+ ஆண்டுகள்',
    maintenance: 'பராமரிப்பு',
    maintenanceDesc: 'கிளைகளை வெட்டுதல், உரமிடுதல், நோய் கண்காணிப்பு',
    ongoing: 'தொடர்ச்சியாக',
    
    // Government Schemes
    governmentSchemesForFarmers: 'விவசாயிகளுக்கு கிடைக்கும் அரசு திட்டங்களை உலாவவும் மற்றும் விண்ணப்பிக்கவும்',
    availableSchemes: 'கிடைக்கும் திட்டங்கள்',
    eligibility: 'தகுதி',
    benefits: 'நன்மைகள்',
    howToApply: 'எப்படி விண்ணப்பிப்பது',
    applyNow: 'இப்போது விண்ணப்பிக்கவும்',
    deadline: 'கடைசி நாள்',
    
    // Scheme Titles
    scheme_pmksy: 'பிரதம மந்திரி கிருஷி சிஞ்சாய் யோஜனா',
    scheme_nfsm: 'தேசிய உணவு பாதுகாப்பு பணி',
    scheme_rkvy: 'ராஷ்ட்ரிய கிருஷி விகாஸ் யோஜனா',
    scheme_nhm: 'தேசிய தோட்டக்கலை பணி',
    scheme_pmfme: 'பிஎம் நுண்ணிய உணவு பதப்படுத்தும் நிறுவனங்களை முறைப்படுத்துதல்',
    scheme_agri_mech_tn: 'வேளாண் இயந்திரமயமாக்கல் திட்டம் (TN)',
    scheme_organic_kl: 'இயற்கை விவசாய மேம்பாட்டு திட்டம் (KL)',
    scheme_pmkmdy: 'பிரதம மந்திரி கிஷான் மான் தன் யோஜனா',
    scheme_pmay: 'பிரதம மந்திரி ஆவாஸ் யோஜனா (கிராமின்)',
    scheme_nlm: 'தேசிய கால்நடை வளர்ப்பு பணி',
    scheme_pmmsy: 'பிரதம மந்திரி மத்ஸ்ய சம்பதா யோஜனா',
    scheme_ami_tn: 'வேளாண் சந்தைப்படுத்தல் உள்கட்டமைப்பு (TN)',
    scheme_shc: 'மண் ஆரோக்கிய அட்டை திட்டம்',
    scheme_wbci: 'வானிலை அடிப்படையிலான பயிர் காப்பீட்டு திட்டம்',
    scheme_mif_tn: 'நுண் நீர்ப்பாசன நிதி (TN)',
    scheme_fwf_kl: 'விவசாயிகள் நலவாரியம் (KL)',
    scheme_atma: 'வேளாண் தொழில்நுட்ப மேலாண்மை நிறுவனம்',
    scheme_nmoop: 'எண்ணெய் வித்துக்கள் மற்றும் பனை எண்ணெய் தேசிய பணி',
    scheme_pmgkra: 'பிஎம் கரீப் கல்யாண் ரோஜ்கார் அபியான்',
    scheme_isam: 'ஒருங்கிணைந்த வேளாண் சந்தைப்படுத்தல் திட்டம்',
    scheme_pmsampada: 'பிரதம மந்திரி கிஷான் சம்பதா யோஜனா',
    scheme_nmsa: 'நிலையான வேளாண்மைக்கான தேசிய பணி',
    scheme_pmkusum: 'பிரதம மந்திரி கிஷான் ஊர்ஜா சுரக்ஷா யோஜனா',
    scheme_pmabhy: 'பிஎம் ஆத்மநிர்பர் ஸ்வஸ்த் பாரத் யோஜனா',
    
    // Scheme Descriptions
    scheme_pmksy_desc: 'விவசாயிகளுக்கு திறமையான நீர்ப்பாசனம் மற்றும் நீர் சேமிப்பை ஊக்குவிக்கிறது',
    scheme_nfsm_desc: 'அரிசி, கோதுமை, பருப்பு வகைகள் மற்றும் கரடுமுரடான தானியங்களின் உற்பத்தியை அதிகரிக்க ஊக்கத்தொகைகள்',
    scheme_rkvy_desc: 'மாநில அளவிலான வேளாண் மேம்பாட்டு திட்டங்களுக்கு நிதி',
    scheme_nhm_desc: 'தோட்டக்கலை பயிர்கள், நர்சரிகள் மற்றும் அறுவடைக்கு பின் மேலாண்மைக்கு ஆதரவு',
    scheme_pmfme_desc: 'நுண்ணிய உணவு பதப்படுத்தும் நிறுவனங்களை மேம்படுத்துதல் மற்றும் முறைப்படுத்துதலுக்கு ஆதரவு',
    scheme_agri_mech_tn_desc: 'டிராக்டர்கள், சக்தி இயந்திரங்கள் மற்றும் பண்ணை இயந்திரங்கள் கொள்முதலுக்கு மானியம்',
    scheme_organic_kl_desc: 'கேரளாவில் இயற்கை விவசாயத்திற்கு பயிற்சி மற்றும் உள்ளீடு ஆதரவு',
    scheme_pmkmdy_desc: 'சிறு மற்றும் குறு விவசாயிகளுக்கு 60 வயதிற்கு பிறகு ஓய்வூதிய திட்டம்',
    scheme_pmay_desc: 'கிராமப்புற பகுதிகளில் வீடு கட்டுவதற்கு நிதி உதவி',
    scheme_nlm_desc: 'கால்நடை வளர்ச்சி, தீவனம் மற்றும் தீவனத்திற்கு ஆதரவு',
    scheme_pmmsy_desc: 'மீன்வளம் மற்றும் நீர்வாழ் உயிர் வளர்ப்பு மேம்பாட்டிற்கு ஆதரவு',
    scheme_ami_tn_desc: 'சந்தை மையங்கள், குளிர்பதன கிடங்குகள் மற்றும் பதப்படுத்தும் அலகுகள் உருவாக்கத்திற்கு ஆதரவு',
    scheme_shc_desc: 'சிறந்த பயிர் மேலாண்மைக்கு மண் சோதனை மற்றும் ஆரோக்கிய அட்டை வினியோகம்',
    scheme_wbci_desc: 'பாதகமான வானிலையால் பயிர் இழப்புக்கு காப்பீட்டு கவரேஜ்',
    scheme_mif_tn_desc: 'நுண் நீர்ப்பாசன திட்டங்களுக்கு கடன் மற்றும் ஆதரவு',
    scheme_fwf_kl_desc: 'கேரளாவில் விவசாயிகளுக்கு ஓய்வூதியம் மற்றும் நல ஆதரவு',
    scheme_atma_desc: 'புதிய வேளாண் தொழில்நுட்பங்களின் பயிற்சி மற்றும் விளக்கம்',
    scheme_nmoop_desc: 'எண்ணெய் வித்துக்கள் மற்றும் பனை எண்ணெய் சாகுபடிக்கு ஆதரவு',
    scheme_pmgkra_desc: 'புலம்பெயர்ந்த தொழிலாளர்களுக்கு ஊதிய வேலைவாய்ப்பு மற்றும் கிராமப்புற உள்கட்டமைப்பு',
    scheme_isam_desc: 'சந்தைப்படுத்தல் உள்கட்டமைப்பு மற்றும் இ-NAM ஒருங்கிணைப்புக்கு ஆதரவு',
    scheme_pmsampada_desc: 'உணவு பதப்படுத்துதல் மற்றும் மதிப்பு கூட்டலுக்கு ஆதரவு',
    scheme_nmsa_desc: 'காலநிலை-தாங்கும் வேளாண்மைக்கு பயிற்சி மற்றும் ஆதரவு',
    scheme_pmkusum_desc: 'சூரிய பம்புகள் மற்றும் மின்சாரக் கட்ட சூரிய சக்தி நிலையங்கள் நிறுவலுக்கு ஆதரவு',
    scheme_pmabhy_desc: 'கிராமப்புற பகுதிகளில் சுகாதாரம் மற்றும் ஆரோக்கிய மையங்களுக்கு ஆதரவு',
  },
  ml: {
    // Navigation - Malayalam
    home: 'ഹോം',
    dashboard: 'ഡാഷ്ബോർഡ്',
    voiceAssistant: 'വോയ്സ് അസിസ്റ്റന്റ്',
    imageAnalysis: 'ഇമേജ് അനാലിസിസ്',
    cropAdvisory: 'ക്രോപ് അഡ്വൈസറി',
    weather: 'കാലാവസ്ഥ',
    soilHealth: 'മണ്ണിന്റെ ആരോഗ്യം',
    governmentSchemes: 'സർക്കാർ പദ്ധതികൾ',
    diseaseManagement: 'രോഗ നിയന്ത്രണം',
    cultivationGuide: 'കൃഷി ഗൈഡ്',

    // Common
    login: 'ലോഗിൻ',
    register: 'രജിസ്റ്റർ',
    logout: 'ലോഗൗട്ട്',
    submit: 'സമർപ്പിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    save: 'സേവ് ചെയ്യുക',
    delete: 'ഇല്ലാതാക്കുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    search: 'തിരയുക',

    // Home Page
    welcomeTitle: 'AI അധിഷ്ഠിത കാർഷിക ഉപദേശക സംവിധാനം',
    welcomeSubtitle: 'തമിഴ്നാട് & കേരള കർഷകരെ ശാക്തീകരിക്കുന്നു',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    getStarted: 'ആരംഭിക്കുക',

    // Features
    voiceSupport: 'വോയ്സ് പിന്തുണ',
    voiceSupportDesc: 'നിങ്ങളുടെ ഇഷ്ട ഭാഷയിൽ വോയ്സ് ഉപയോഗിച്ച് ചോദ്യങ്ങൾ ചോദിക്കുക',
    diseaseDetection: 'രോഗ നിർണ്ണയം',
    diseaseDetectionDesc: 'AI പവേർഡ് ഡിസീസ് അനാലിസിസിനായി ക്രോപ് ഇമേജുകൾ അപ്ലോഡ് ചെയ്യുക',
    expertAdvice: 'വിദഗ്ധ ഉപദേശം',
    expertAdviceDesc: 'വ്യക്തിഗതമാക്കിയ കൃഷി, ക്രോപ് മാനേജ്മെന്റ് ടിപ്സുകൾ നേടുക',
    weatherInsights: 'കാലാവസ്ഥാ സൂചനകൾ',
    weatherInsightsDesc: 'മികച്ച ആസൂത്രണത്തിനായി തത്സമയ കാലാവസ്ഥാ ഡാറ്റയും കാർഷിക പ്രവചനങ്ങളും',
    soilHealthFeature: 'മണ്ണിന്റെ ആരോഗ്യം',
    soilHealthFeatureDesc: 'സമഗ്രമായ മണ്ണ് വിശകലനവും മെച്ചപ്പെടുത്തൽ ശുപാർശകളും',
    governmentSchemesFeature: 'സർക്കാർ പദ്ധതികൾ',
    governmentSchemesFeatureDesc: 'കർഷകർക്കുള്ള ഏറ്റവും പുതിയ സബ്സിഡികളും പിന്തുണാ പദ്ധതികളും ആക്സസ് ചെയ്യുക',
    farmersHelped: 'സഹായിച്ച കർഷകർ',
    accuracyRate: 'കൃത്യത നിരക്ക്',
    supportAvailable: 'പിന്തുണ ലഭ്യമാണ്',
    comprehensiveAgriSolutions: 'സമഗ്ര കാർഷിക പരിഹാരങ്ങൾ',
    everythingInOnePlace: 'വിവേകപൂർണ്ണമായ കൃഷി തീരുമാനങ്ങൾ എടുക്കാൻ നിങ്ങൾക്ക് ആവശ്യമുള്ളതെല്ലാം ഒരിടത്ത്',
    joinSmartFarmers: 'ആയിരക്കണക്കിന് സ്മാർട്ട് കർഷകരോട് ചേരുക',
    startJourneyDesc: 'AI പവേർഡ് സൂചനകളും വിദഗ്ധ മാർഗ്ഗനിർദ്ദേശവും ഉപയോഗിച്ച് ഡാറ്റാ അധിഷ്ഠിത കൃഷിയിലേക്കുള്ള നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക.',
    startFreeToday: 'ഇന്ന് സൗജന്യമായി ആരംഭിക്കുക',
    footerCopyright: '© 2024 KisanAi. AI സാങ്കേതികവിദ്യയുമായി കർഷകരെ ശാക്തീകരിക്കുന്നു.',
    moreServices: 'കൂടുതൽ സേവനങ്ങൾ',

    // Dashboard
    welcomeBack: 'തിരികെ സ്വാഗതം',
    farmer: 'കർഷകൻ',
    farmerName: 'കർഷകന്റെ പേര്',
    farmerProfile: 'കർഷക പ്രൊഫൈൽ',
    farmSize: 'ഫാം വലുപ്പം',
    mainCrops: 'പ്രധാന വിളകൾ',
    location: 'സ്ഥലം',
    notSpecified: 'വ്യക്തമാക്കിയിട്ടില്ല',
    quickActions: 'ദ്രുത പ്രവർത്തനങ്ങൾ',
    startNow: 'ഇപ്പോൾ ആരംഭിക്കുക',
    askQuestionsVoice: 'വോയ്സ് ഉപയോഗിച്ച് ചോദ്യങ്ങൾ ചോദിക്കുക',
    uploadCropImages: 'വിശകലനത്തിനായി ക്രോപ് ഇമേജുകൾ അപ്ലോഡ് ചെയ്യുക',
    getCropRecommendations: 'ക്രോപ് ശുപാർശകൾ നേടുക',
    weatherForecastAlerts: 'കാലാവസ്ഥാ പ്രവചനം & അലേർട്ടുകൾ',
    agriculturalDashboard: 'ഇന്നത്തെ നിങ്ങളുടെ കാർഷിക ഡാഷ്ബോർഡ് ഇതാ',
    additionalServices: 'അധിക സേവനങ്ങൾ',
    todayWeather: 'ഇന്നത്തെ കാലാവസ്ഥ',
    temperature: 'താപനില',
    humidity: 'ഈർപ്പം',
    condition: 'അവസ്ഥ',
    rainfall: 'മഴ',
    rainfallExpected: 'പ്രതീക്ഷിക്കുന്നു',
    partlyCloudy: 'ഭാഗികമായി മേഘാവൃതം',
    hazy: 'മൂടൽമഞ്ഞ്',
    noRainExpected: 'മഴ പ്രതീക്ഷിക്കുന്നില്ല',
    uvIndex: 'UV സൂചിക',
    weatherAlerts: 'കാലാവസ്ഥ അലേർട്ടുകൾ',
    farmingAdvice: 'കൃഷി ഉപദേശം',
    enterLocation: 'നിങ്ങളുടെ സ്ഥലം നൽകുക (ഉദാ., കോയമ്പത്തൂർ, തമിഴ്നാട്)',
    precipitation: 'മഴ',
    high: 'ഉയർന്നത്',
    low: 'താഴ്ന്നത്',
    currentWeather: 'നിലവിലെ കാലാവസ്ഥ',
    windSpeed: 'കാറ്റിന്റെ വേഗത',
    visibility: 'ദൃശ്യപരത',
    sevenDayForecast: '7 ദിവസ പ്രവചനം',
    getWeather: 'കാലാവസ്ഥ നേടുക',
    realTimeWeatherData: 'മികച്ച കൃഷി തീരുമാനങ്ങൾക്കായി തത്സമയ കാലാവസ്ഥ ഡാറ്റയും കാർഷിക പ്രവചനങ്ങളും',
    clouds: 'മേഘങ്ങൾ',
    sunny: 'വെയിലുള്ള',
    rainy: 'മഴ',
    // Weather Conditions
    weatherClouds: 'മേഘങ്ങൾ',
    weatherClear: 'തെളിഞ്ഞത്',
    weatherRain: 'മഴ',
    weatherDrizzle: 'ചാറ്റൽമഴ',
    weatherThunderstorm: 'ഇടിമിന്നലോടുകൂടിയ മഴ',
    weatherSnow: 'മഞ്ഞ്',
    weatherMist: 'മൂടൽമഞ്ഞ്',
    weatherHaze: 'പൊടിപടലം',
    weatherFog: 'കട്ടിയുള്ള മൂടൽമഞ്ഞ്',
    weatherDust: 'പൊടി',
    weatherSmoke: 'പുക',

    // Login
    signInAccount: 'നിങ്ങളുടെ അക്കൗണ്ടിലേക്ക് സൈൻ ഇൻ ചെയ്യുക',
    welcomeBackAdvisor: 'നിങ്ങളുടെ കാർഷിക ഉപദേഷ്ടാവിലേക്ക് തിരികെ സ്വാഗതം',
    emailAddress: 'ഇമെയിൽ വിലാസം',
    password: 'പാസ്വേഡ്',
    enterPassword: 'നിങ്ങളുടെ പാസ്വേഡ് നൽകുക',
    forgotPassword: 'പാസ്വേഡ് മറന്നോ?',
    noAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    registerNow: 'ഇപ്പോൾ രജിസ്റ്റർ ചെയ്യുക',

    // Register
    createAccount: 'നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    joinFarmers: 'AI സാങ്കേതികവിദ്യ ഉപയോഗിക്കുന്ന ആയിരക്കണക്കിന് കർഷകരോട് ചേരുക',
    name: 'പേര്',
    fullName: 'മുഴുവൻ പേര്',
    phoneNumber: 'ഫോൺ നമ്പർ',
    confirmPassword: 'പാസ്വേഡ് സ്ഥിരീകരിക്കുക',
    state: 'സംസ്ഥാനം',
    selectState: 'നിങ്ങളുടെ സംസ്ഥാനം തിരഞ്ഞെടുക്കുക',
    tamilNadu: 'തമിഴ്നാട്',
    kerala: 'കേരളം',
    mainCropsGrow: 'നിങ്ങൾ വളർത്തുന്ന പ്രധാന വിളകൾ',
    alreadyAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    loginNow: 'ഇപ്പോൾ ലോഗിൻ ചെയ്യുക',

    // Voice Assistant
    askQuestionsAboutFarming: 'നിങ്ങളുടെ ഇഷ്ട ഭാഷയിൽ വോയ്സ് അല്ലെങ്കിൽ ടെക്സ്റ്റ് ഉപയോഗിച്ച് കൃഷിയെക്കുറിച്ച് ചോദ്യങ്ങൾ ചോദിക്കുക',
    speakOrType: 'നിങ്ങളുടെ ചോദ്യം സംസാരിക്കുക അല്ലെങ്കിൽ ടൈപ്പ് ചെയ്യുക',
    startRecording: 'റെക്കോർഡിംഗ് ആരംഭിക്കുക',
    stopRecording: 'റെക്കോർഡിംഗ് നിർത്തുക',
    listening: 'കേൾക്കുന്നു...',
    stopSpeaking: 'സംസാരിക്കുന്നത് നിറുത്തുക',
    voiceOutput: 'ശബ്ദ ഔട്ട്പുട്ട്',
    typeQuestion: 'നിങ്ങളുടെ ചോദ്യം ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
    send: 'അയയ്ക്കുക',
    sampleQuestions: 'സാമ്പിൾ ചോദ്യങ്ങൾ',
    processing: 'പ്രോസസ്സ് ചെയ്യുന്നു...',
    welcomeMessage: 'ഹലോ! ഞാൻ നിങ്ങളുടെ കാർഷിക AI അസിസ്റ്റന്റ് ആണ്. തമിഴ്നാട്, കേരളത്തിലെ കൃഷി, വിളകൾ, രോഗങ്ങൾ അല്ലെങ്കിൽ കാലാവസ്ഥ എന്നിവയെക്കുറിച്ച് എന്തും എന്നോട് ചോദിക്കുക.',
    question1: 'മൺസൂൺ സീസണിലെ ഏറ്റവും നല്ല വിളകൾ?',
    question2: 'റൈസ് ബ്ലാസ്റ്റ് രോഗം എങ്ങനെ നിയന്ത്രിക്കാം?',
    question3: 'തേങ്ങ വളപ്രയോഗ ഷെഡ്യൂൾ?',
    question4: 'അടുത്ത ആഴ്ചയിലേക്കുള്ള കാലാവസ്ഥ പ്രവചനം?',
    question5: 'ഓർഗാനിക് കീട നിയന്ത്രണ രീതികൾ?',
    question6: 'കർഷകർക്കുള്ള സർക്കാർ പദ്ധതികൾ?',

    // Image Analysis
    uploadCropImagesAnalysis: 'AI പവേർഡ് രോഗനിർണയത്തിനും വിശകലനത്തിനുമായി ക്രോപ് ഇമേജുകൾ അപ്ലോഡ് ചെയ്യുക',
    dragDropImage: 'ഒരു ചിത്രം ഇവിടെ ഡ്രാഗ് ആൻഡ് ഡ്രോപ്പ് ചെയ്യുക',
    or: 'അല്ലെങ്കിൽ',
    browseFiles: 'ഫയലുകൾ ബ്രൗസ് ചെയ്യുക',
    analyzeImage: 'ഇമേജ് വിശകലനം ചെയ്യുക',
    analyzing: 'വിശകലനം ചെയ്യുന്നു...',
    analysisResults: 'വിശകലന ഫലങ്ങൾ',
    diseaseStatus: 'രോഗ നില',
    detected: 'കണ്ടെത്തി',
    noDisease: 'രോഗം കണ്ടെത്തിയില്ല',
    confidence: 'വിശ്വാസം',
    severity: 'തീവ്രത',
    affectedArea: 'ബാധിത പ്രദേശം',
    recommendations: 'ശുപാർശകൾ',
    treatment: 'ചികിത്സ',
    prevention: 'പ്രതിരോധം',
    uploadNewImage: 'പുതിയ ഇമേജ് അപ്ലോഡ് ചെയ്യുക',
    additionalInformation: 'അധിക വിവരങ്ങൾ',
    cropTypeOptional: 'ക്രോപ് തരം (ഓപ്ഷണൽ)',
    cropTypePlaceholder: 'ഉദാ., നെല്ല്, തേങ്ങ, നിലക്കടല',
    symptomsNotesOptional: 'ലക്ഷണങ്ങൾ/കുറിപ്പുകൾ (ഓപ്ഷണൽ)',
    symptomsPlaceholder: 'നിങ്ങൾ നിരീക്ഷിച്ച ലക്ഷണങ്ങൾ വിവരിക്കുക...',
    analyzingImage: 'ഇമേജ് വിശകലനം ചെയ്യുന്നു...',
    readyToAnalyze: 'വിശകലനത്തിന് തയ്യാറാണ്',
    readyToAnalyzeDesc: 'നിങ്ങളുടെ ക്രോപ്പിന്റെ വ്യക്തമായ ഇമേജ് അപ്ലോഡ് ചെയ്ത് AI പവേർഡ് രോഗനിർണയ ഫലങ്ങൾ ലഭിക്കാൻ വിശകലനം ചെയ്യുക.',
    tipsForBetterAnalysis: 'മികച്ച വിശകലനത്തിനുള്ള നുറുങ്ങുകൾ',
    clearImages: 'വ്യക്തമായ ചിത്രങ്ങൾ',
    clearImagesDesc: 'ബാധിത പ്രദേശങ്ങൾ വ്യക്തമായി കാണിക്കുന്ന നല്ല വെളിച്ചമുള്ള ഫോട്ടോകൾ എടുക്കുക',
    closeUpShots: 'ക്ലോസ്-അപ്പ് ഷോട്ടുകൾ',
    closeUpShotsDesc: 'പുള്ളികൾ, നിറം മാറ്റം അല്ലെങ്കിൽ കേടുപാടുകൾ പോലുള്ള പ്രത്യേക ലക്ഷണങ്ങളിൽ ശ്രദ്ധിക്കുക',
    additionalInfo: 'അധിക വിവരങ്ങൾ',
    additionalInfoDesc: 'കൂടുതൽ കൃത്യമായ ഫലങ്ങൾക്ക് ക്രോപ് തരവും ലക്ഷണ വിശദാംശങ്ങളും നൽകുക',
    changeImage: 'ഇമേജ് മാറ്റുക',
    confidenceScore: 'വിശ്വാസ സ്കോർ',
    healthStatus: 'ആരോഗ്യ നില',
    recommendedTreatment: 'ശുപാർശ ചെയ്ത ചികിത്സ',
    preventionTips: 'പ്രതിരോധ നുറുങ്ങുകൾ',
    saveReport: 'റിപ്പോർട്ട് സേവ് ചെയ്യുക',
    shareResults: 'ഫലങ്ങൾ പങ്കിടുക',

    // Crop Advisory
    farmDetails: 'ഫാം വിശദാംശങ്ങൾ',
    locationDistrict: 'സ്ഥലം/ജില്ല',
    locationPlaceholder: 'ഉദാ., കോയമ്പത്തൂർ, തൃശ്ശൂർ',
    selectSoilType: 'മണ്ണ് തരം തിരഞ്ഞെടുക്കുക',
    clayey: 'കളിമണ്ണ്',
    sandy: 'മണൽ',
    loamy: 'വളക്കൂറുള്ള',
    redSoil: 'ചുവന്ന മണ്ണ്',
    blackSoil: 'കറുത്ത മണ്ണ്',
    laterite: 'ലാറ്ററൈറ്റ്',
    alluvial: 'എക്കൽ മണ്ണ്',
    farmSizePlaceholder: 'ഉദാ., 2 ഏക്കർ',
    preferredSeason: 'ഇഷ്ടപ്പെട്ട സീസൺ',
    selectSeason: 'സീസൺ തിരഞ്ഞെടുക്കുക',
    kharif: 'ഖാരിഫ് (ജൂൺ-ഒക്ടോബർ)',
    rabi: 'റബി (ഒക്ടോബർ-മാർച്ച്)',
    summer: 'വേനൽക്കാലം (മാർച്ച്-ജൂൺ)',
    perennialCrops: 'ബഹുവർഷ വിളകൾ',
    waterSource: 'ജലസ്രോതസ്സ്',
    selectWaterSource: 'ജലസ്രോതസ്സ് തിരഞ്ഞെടുക്കുക',
    rainFed: 'മഴയെ ആശ്രയിച്ച്',
    irrigationSource: 'ജലസേചനം',
    borewell: 'ബോർവെൽ',
    canal: 'കനാൽ',
    river: 'നദി',
    analyzingCrops: 'വിശകലനം ചെയ്യുന്നു...',
    currentConditions: 'നിലവിലെ അവസ്ഥകൾ',
    rainfallLabel: 'മഴ:',
    temperatureLabel: 'താപനില:',
    humidityLabel: 'ഈർപ്പം:',
    expected: 'പ്രതീക്ഷിക്കുന്നു',
    cropRecommendations: 'ക്രോപ് ശുപാർശകൾ',
    cropsFound: 'വിളകൾ കണ്ടെത്തി',
    suitability: 'അനുയോജ്യത',
    soilTypes: 'മണ്ണ് തരങ്ങൾ',
    demand: 'ഡിമാൻഡ്',
    risk: 'റിസ്ക്',
    advantages: 'ഗുണങ്ങൾ',
    challenges: 'വെല്ലുവിളികൾ',
    readyForRecommendations: 'ശുപാർശകൾക്ക് തയ്യാറാണ്',
    readyForRecommendationsDesc: 'ഇടതുവശത്ത് നിങ്ങളുടെ ഫാം വിശദാംശങ്ങൾ പൂരിപ്പിച്ച് വ്യക്തിഗതമാക്കിയ ക്രോപ് നിർദ്ദേശങ്ങൾ ലഭിക്കാൻ "ശുപാർശകൾ നേടുക" ക്ലിക്ക് ചെയ്യുക.',

    // Crop Advisory
    getCropAdvisoryRecommendations: 'നിങ്ങളുടെ അവസ്ഥകളുടെ അടിസ്ഥാനത്തിൽ ക്രോപ് അഡ്വൈസറിയും വ്യക്തിഗത ശുപാർശകളും നേടുക',
    selectCropType: 'ക്രോപ് തരം തിരഞ്ഞെടുക്കുക',
    soilType: 'മണ്ണിന്റെ തരം',
    season: 'സീസൺ',
    getRecommendations: 'ശുപാർശകൾ നേടുക',
    fetching: 'ലഭ്യമാക്കുന്നു...',
    advisory: 'ഉപദേശം',
    bestPractices: 'മികച്ച രീതികൾ',
    expectedYield: 'പ്രതീക്ഷിക്കുന്ന വിളവ്',
    waterRequirements: 'ജല ആവശ്യങ്ങൾ',
    fertilizerNeeds: 'വളം ആവശ്യങ്ങൾ',
    commonPests: 'സാധാരണ കീടങ്ങൾ',
    harvestTime: 'വിളവെടുപ്പ് സമയം',

    // Soil Health
    soilTestingAndHealth: 'ഒപ്റ്റിമൽ ക്രോപ് വളർച്ചയ്ക്കുള്ള മണ്ണ് പരിശോധനയും ആരോഗ്യ നിരീക്ഷണവും',
    requestSoilTest: 'മണ്ണ് പരിശോധന അഭ്യർത്ഥിക്കുക',
    viewReports: 'റിപ്പോർട്ടുകൾ കാണുക',
    soilNutrients: 'മണ്ണിലെ പോഷകങ്ങൾ',
    nitrogen: 'നൈട്രജൻ',
    phosphorus: 'ഫോസ്ഫറസ്',
    potassium: 'പൊട്ടാസ്യം',
    organic: 'ഓർഗാനിക്',
    phLevel: 'pH ലെവൽ',
    optimal: 'ഒപ്റ്റിമൽ',

    // Government Schemes
    governmentSchemesForFarmers: 'കർഷകർക്ക് ലഭ്യമായ സർക്കാർ പദ്ധതികൾ ബ്രൗസ് ചെയ്ത് അപേക്ഷിക്കുക',
    availableSchemes: 'ലഭ്യമായ പദ്ധതികൾ',
    eligibility: 'യോഗ്യത',
    benefits: 'നേട്ടങ്ങൾ',
    howToApply: 'എങ്ങനെ അപേക്ഷിക്കാം',
    applyNow: 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    deadline: 'അവസാന തീയതി',

    // Disease Management
    identifyManageDiseases: 'വിദഗ്ധ മാർഗ്ഗനിർദ്ദേശത്തോടെ ക്രോപ് രോഗങ്ങൾ തിരിച്ചറിയുകയും കൈകാര്യം ചെയ്യുകയും ചെയ്യുക',
    commonDiseases: 'സാധാരണ രോഗങ്ങൾ',
    symptoms: 'ലക്ഷണങ്ങൾ',
    causes: 'കാരണങ്ങൾ',
    control: 'നിയന്ത്രണം',
    organicSolutions: 'ഓർഗാനിക് പരിഹാരങ്ങൾ',
    chemicalTreatment: 'രാസ ചികിത്സ',

    // Cultivation Guide
    stepByStepGuide: 'വിവിധ വിളകൾക്കുള്ള ഘട്ടം ഘട്ടമായുള്ള കൃഷി ഗൈഡുകൾ',
    selectCrop: 'വിള തിരഞ്ഞെടുക്കുക',
    landPreparation: 'ഭൂമി തയ്യാറാക്കൽ',
    sowing: 'വിതയ്ക്കൽ',
    irrigation: 'ജലസേചനം',
    weeding: 'കളപറിക്കൽ',
    harvesting: 'വിളവെടുപ്പ്',
    postHarvest: 'വിളവെടുപ്പിന് ശേഷം',
    duration: 'കാലയളവ്',
    investment: 'നിക്ഷേപം',

    // Soil Health Page
    soilHealthDesc: 'മികച്ച വിള വിളവിനായി നിങ്ങളുടെ മണ്ണ് ഘടന വിശകലനം ചെയ്ത് വ്യക്തിഗതമാക്കിയ ശുപാർശകൾ നേടുക',
    soilTestData: 'മണ്ണ് പരിശോധന ഡാറ്റ',
    sampleLocation: 'സാമ്പിൾ സ്ഥലം',
    sampleLocationPlaceholder: 'ഉദാ., ഫാം ബ്ലോക്ക് A, കോയമ്പത്തൂർ',
    sampleDate: 'സാമ്പിൾ തീയതി',
    depthCm: 'ആഴം (സെ.മീ)',
    nutrientLevelsOptional: 'പോഷക നിലകൾ (ഓപ്ഷണൽ)',
    organicMatterPercent: 'ഓർഗാനിക് മാറ്റർ (%)',
    nitrogenKgHa: 'നൈട്രജൻ (കിലോ/ഹെക്ടേർ)',
    phosphorusKgHa: 'ഫോസ്ഫറസ് (കിലോ/ഹെക്ടേർ)',
    potassiumKgHa: 'പൊട്ടാസ്യം (കിലോ/ഹെക്ടേർ)',
    cropPlanned: 'ആസൂത്രണം ചെയ്ത വിള',
    selectCropPlaceholder: 'വിള തിരഞ്ഞെടുക്കുക',
    ricePaddy: 'അരി/നെല്ല്',
    coconut: 'തേങ്ങ',
    groundnut: 'നിലക്കടല',
    banana: 'വാഴ',
    pepper: 'കുരുമുളക്',
    vegetables: 'പച്ചക്കറികൾ',
    millets: 'ചെറുധാന്യങ്ങൾ',
    additionalNotes: 'അധിക കുറിപ്പുകൾ',
    additionalNotesPlaceholder: 'മണ്ണ് അവസ്ഥയെക്കുറിച്ചുള്ള എന്തെങ്കിലും നിരീക്ഷണങ്ങൾ...',
    analyzingSoil: 'വിശകലനം ചെയ്യുന്നു...',
    analyzeSoil: 'മണ്ണ് വിശകലനം ചെയ്യുക',
    overallSoilHealthScore: 'മൊത്തത്തിലുള്ള മണ്ണ് ആരോഗ്യ സ്കോർ',
    excellent: 'മികച്ചത്',
    good: 'നല്ലത്',
    needsImprovement: 'മെച്ചപ്പെടുത്തൽ ആവശ്യമാണ്',
    organicMatter: 'ഓർഗാനിക് മാറ്റർ',
    nutrientRecommendations: 'പോഷക ശുപാർശകൾ',
    recommendedProducts: 'ശുപാർശ ചെയ്ത ഉൽപ്പന്നങ്ങൾ:',
    suitableCrops: 'അനുയോജ്യമായ വിളകൾ',
    improvementTips: 'മെച്ചപ്പെടുത്തൽ നുറുങ്ങുകൾ',
    downloadReport: 'റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    readyToAnalyzeSoil: 'വിശകലനത്തിന് തയ്യാറാണ്',
    readyToAnalyzeSoilDesc: 'ഇടതുവശത്ത് നിങ്ങളുടെ മണ്ണ് പരിശോധന ഡാറ്റ നൽകുക അല്ലെങ്കിൽ മണ്ണ് മെച്ചപ്പെടുത്തലിനുള്ള വ്യക്തിഗത ശുപാർശകൾക്കായി ലാബ് റിപ്പോർട്ട് അപ്ലോഡ് ചെയ്യുക.',
    dontHaveTestData: 'പരിശോധന ഡാറ്റ ഇല്ലേ?',
    generalRecommendationsNote: 'നിങ്ങളുടെ സ്ഥലം മാത്രം നൽകി പൊതുവായ ശുപാർശകൾ ലഭിക്കും!',
    missingInformation: 'വിവരങ്ങൾ കാണുന്നില്ല',
    enterSampleLocation: 'കുറഞ്ഞത് സാമ്പിൾ സ്ഥലം നൽകുക.',
    soilAnalysisComplete: 'വിശകലനം പൂർത്തിയായി',
    soilAnalysisSuccess: 'മണ്ണ് ആരോഗ്യ വിശകലനം വിജയകരമായി സൃഷ്ടിച്ചു.',

    // Disease Management Page
    diseaseManagementDesc: 'വിദഗ്ധ മാർഗ്ഗനിർദ്ദേശത്തോടെ വിള രോഗങ്ങൾ തിരിച്ചറിയുക, ചികിത്സിക്കുക, പ്രതിരോധിക്കുക',
    searchDiseasesPlaceholder: 'രോഗങ്ങൾ, ലക്ഷണങ്ങൾ അല്ലെങ്കിൽ വിളകൾ തിരയുക...',
    highRisk: 'ഉയർന്ന റിസ്ക്',
    mediumRisk: 'മിതമായ റിസ്ക്',
    lowRisk: 'കുറഞ്ഞ റിസ്ക്',
    riceBlast: 'നെല്ല് ബ്ലാസ്റ്റ്',
    riceBlastSymptoms: 'ഇലകളിൽ മഞ്ഞ വളയങ്ങളുള്ള തവിട്ടു നിറത്തിലുള്ള പുള്ളികൾ',
    riceBlastTreatment: 'ട്രൈസൈക്ലാസോൾ ഫംഗിസൈഡ് പ്രയോഗിക്കുക',
    riceBlastPrevention: 'പ്രതിരോധശേഷിയുള്ള ഇനങ്ങൾ ഉപയോഗിക്കുക, ശരിയായ ഡ്രെയിനേജ്',
    coconutRootWilt: 'തെങ്ങ് വേര് ചീയൽ',
    coconutRootWiltSymptoms: 'പുറം ഇലകൾ മഞ്ഞനിറമാകൽ, തേങ്ങ ഉൽപാദനം കുറയൽ',
    coconutRootWiltTreatment: 'സന്തുലിത വളത്തോടെ വേര് ഊട്ടൽ',
    coconutRootWiltPrevention: 'ശരിയായ ഡ്രെയിനേജ്, ഓർഗാനിക് പദാർത്ഥം ചേർക്കൽ',

    // Cultivation Guide Page
    cultivationGuideDesc: 'തമിഴ്നാട്, കേരളത്തിലെ പ്രധാന വിളകൾക്കുള്ള ഘട്ടം ഘട്ടമായുള്ള കൃഷി ഗൈഡുകൾ',
    paddy: 'നെല്ല്',
    paddyRice: 'നെല്ല് (അരി)',
    coconutCrop: 'തേങ്ങ',
    cultivationGuideTitle: 'കൃഷി ഗൈഡ്',
    landPreparationDesc: 'വയൽ ഉഴുക, നിലം സമതലമാക്കുക, നഴ്സറി കിടക്കകൾ തയ്യാറാക്കുക',
    landPreparationDuration: '15 ദിവസം',
    sowingTransplanting: 'വിതയ്ക്കൽ/നടീൽ',
    sowingTransplantingDesc: 'നഴ്സറിയിൽ വിത്ത് വിതയ്ക്കുക, 30 ദിവസം പ്രായമുള്ള തൈകൾ നടുക',
    sowingTransplantingDuration: '30-35 ദിവസം',
    vegetativeGrowth: 'സസ്യ വളർച്ച',
    vegetativeGrowthDesc: 'വളങ്ങൾ പ്രയോഗിക്കുക, ജല നിലവാരം നിലനിർത്തുക, കള നിയന്ത്രണം',
    vegetativeGrowthDuration: '40-50 ദിവസം',
    reproductivePhase: 'പ്രത്യുൽപാദന ഘട്ടം',
    reproductivePhaseDesc: 'കതിർ രൂപീകരണം, പൂവിടൽ, ധാന്യ രൂപീകരണം',
    reproductivePhaseDuration: '30-35 ദിവസം',
    maturation: 'പക്വത',
    maturationDesc: 'ധാന്യം നിറയ്ക്കൽ, വിളവെടുപ്പിന് മുമ്പ് വയൽ ഉണക്കൽ',
    maturationDuration: '30 ദിവസം',
    siteSelection: 'സ്ഥല തിരഞ്ഞെടുപ്പ്',
    siteSelectionDesc: 'നന്നായി ഡ്രെയിനേജ് ഉള്ള തീരദേശ അല്ലെങ്കിൽ ഉൾനാടൻ പ്രദേശങ്ങൾ തിരഞ്ഞെടുക്കുക',
    initial: 'ആരംഭം',
    planting: 'നടീൽ',
    plantingDesc: 'ശരിയായ അകലത്തോടെ ഗുണനിലവാരമുള്ള തൈകൾ നടുക (7.5 മീ x 7.5 മീ)',
    oneMonth: '1 മാസം',
    youngPalmCare: 'ഇളം തെങ്ങ് പരിചരണം',
    youngPalmCareDesc: 'നിരന്തര ജലസേചനം, വളപ്രയോഗം, കീട നിയന്ത്രണം',
    threeToFiveYears: '3-5 വർഷം',
    bearingStage: 'കായ്ക്കുന്ന ഘട്ടം',
    bearingStageDesc: 'ഓരോ 45 ദിവസത്തിലും സ്ഥിരമായ വിളവെടുപ്പ്, തുടർച്ചയായ പരിചരണം',
    fivePlusYears: '5+ വർഷം',
    maintenance: 'പരിപാലനം',
    maintenanceDesc: 'വെട്ടിനിരത്തൽ, വളപ്രയോഗം, രോഗ നിരീക്ഷണം',
    ongoing: 'തുടർച്ചയായ',
  },
  hi: {
    // Navigation - Hindi
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    voiceAssistant: 'वॉयस असिस्टेंट',
    imageAnalysis: 'छवि विश्लेषण',
    cropAdvisory: 'फसल सलाह',
    weather: 'मौसम',
    soilHealth: 'मिट्टी स्वास्थ्य',
    governmentSchemes: 'सरकारी योजनाएं',
    diseaseManagement: 'रोग प्रबंधन',
    cultivationGuide: 'खेती गाइड',

    // Common
    login: 'लॉगिन',
    register: 'रजिस्टर',
    logout: 'लॉगआउट',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    search: 'खोजें',

    // Home Page
    welcomeTitle: 'AI आधारित कृषि सलाहकार प्रणाली',
    welcomeSubtitle: 'तमिलनाडु और केरल के किसानों को सशक्त बनाना',
    selectLanguage: 'भाषा चुनें',
    getStarted: 'शुरू करें',

    // Features
    voiceSupport: 'वॉयस सपोर्ट',
    voiceSupportDesc: 'अपनी पसंदीदा भाषा में आवाज से सवाल पूछें',
    diseaseDetection: 'रोग पहचान',
    diseaseDetectionDesc: 'AI संचालित रोग विश्लेषण के लिए फसल की तस्वीरें अपलोड करें',
    expertAdvice: 'विशेषज्ञ सलाह',
    expertAdviceDesc: 'व्यक्तिगत खेती और फसल प्रबंधन टिप्स प्राप्त करें',
    weatherInsights: 'मौसम जानकारी',
    weatherInsightsDesc: 'बेहतर योजना के लिए रीयल-टाइम मौसम डेटा और कृषि पूर्वानुमान',
    soilHealthFeature: 'मिट्टी स्वास्थ्य',
    soilHealthFeatureDesc: 'व्यापक मिट्टी विश्लेषण और सुधार सिफारिशें',
    governmentSchemesFeature: 'सरकारी योजनाएं',
    governmentSchemesFeatureDesc: 'किसानों के लिए नवीनतम सब्सिडी और सहायता योजनाओं तक पहुंचें',
    farmersHelped: 'किसानों की मदद',
    accuracyRate: 'सटीकता दर',
    supportAvailable: 'सहायता उपलब्ध',
    comprehensiveAgriSolutions: 'व्यापक कृषि समाधान',
    everythingInOnePlace: 'सूचित खेती निर्णय लेने के लिए आपको जो कुछ भी चाहिए, एक ही स्थान पर',
    joinSmartFarmers: 'हजारों स्मार्ट किसानों से जुड़ें',
    startJourneyDesc: 'AI संचालित अंतर्दृष्टि और विशेषज्ञ मार्गदर्शन के साथ डेटा-चालित खेती की ओर अपनी यात्रा शुरू करें।',
    startFreeToday: 'आज ही मुफ्त शुरू करें',
    footerCopyright: '© 2024 KisanAi. AI तकनीक से किसानों को सशक्त बनाना।',
    moreServices: 'अधिक सेवाएं',

    // Dashboard
    welcomeBack: 'वापस स्वागत है',
    farmer: 'किसान',
    farmerName: 'किसान का नाम',
    farmerProfile: 'किसान प्रोफाइल',
    farmSize: 'खेत का आकार',
    mainCrops: 'मुख्य फसलें',
    location: 'स्थान',
    notSpecified: 'निर्दिष्ट नहीं',
    quickActions: 'त्वरित कार्य',
    startNow: 'अभी शुरू करें',
    askQuestionsVoice: 'आवाज से सवाल पूछें',
    uploadCropImages: 'विश्लेषण के लिए फसल की तस्वीरें अपलोड करें',
    getCropRecommendations: 'फसल सिफारिशें प्राप्त करें',
    weatherForecastAlerts: 'मौसम पूर्वानुमान और अलर्ट',
    agriculturalDashboard: 'आज का आपका कृषि डैशबोर्ड यहाँ है',
    additionalServices: 'अतिरिक्त सेवाएं',
    todayWeather: 'आज का मौसम',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    condition: 'स्थिति',
    rainfall: 'वर्षा',
    rainfallExpected: 'अपेक्षित',
    partlyCloudy: 'आंशिक बादल',
    hazy: 'धुंधला',
    noRainExpected: 'बारिश की उम्मीद नहीं',

    // Login
    signInAccount: 'अपने खाते में साइन इन करें',
    welcomeBackAdvisor: 'अपने कृषि सलाहकार में वापस स्वागत है',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    forgotPassword: 'पासवर्ड भूल गए?',
    noAccount: 'खाता नहीं है?',
    registerNow: 'अभी रजिस्टर करें',

    // Register
    createAccount: 'अपना खाता बनाएं',
    joinFarmers: 'AI तकनीक का उपयोग करने वाले हजारों किसानों से जुड़ें',
    name: 'नाम',
    fullName: 'पूरा नाम',
    phoneNumber: 'फोन नंबर',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    state: 'राज्य',
    selectState: 'अपना राज्य चुनें',
    tamilNadu: 'तमिलनाडु',
    kerala: 'केरल',
    mainCropsGrow: 'आप जो मुख्य फसलें उगाते हैं',
    alreadyAccount: 'पहले से खाता है?',
    loginNow: 'अभी लॉगिन करें',

    // Weather
    uvIndex: 'UV इंडेक्स',
    weatherAlerts: 'मौसम अलर्ट',
    farmingAdvice: 'खेती सलाह',
    enterLocation: 'अपना स्थान दर्ज करें (उदा., कोयंबटूर, तमिलनाडु)',
    precipitation: 'वर्षण',
    high: 'उच्च',
    low: 'न्यून',

    // Voice Assistant
    askQuestionsAboutFarming: 'अपनी पसंदीदा भाषा में आवाज या टेक्स्ट से खेती के बारे में सवाल पूछें',
    speakOrType: 'अपना सवाल बोलें या टाइप करें',
    startRecording: 'रिकॉर्डिंग शुरू करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    listening: 'सुन रहा है...',
    stopSpeaking: 'बोलना बंद करें',
    voiceOutput: 'वॉयस आउटपुट',
    typeQuestion: 'अपना सवाल यहाँ टाइप करें...',
    send: 'भेजें',
    sampleQuestions: 'नमूना प्रश्न',
    processing: 'प्रोसेसिंग...',
    welcomeMessage: 'नमस्ते! मैं आपका कृषि AI सहायक हूं। तमिलनाडु और केरल में खेती, फसलों, रोगों या मौसम के बारे में कुछ भी पूछें।',
    question1: 'मानसून सीजन के लिए सबसे अच्छी फसलें?',
    question2: 'चावल ब्लास्ट रोग का प्रबंधन कैसे करें?',
    question3: 'नारियल उर्वरक अनुसूची?',
    question4: 'अगले सप्ताह का मौसम पूर्वानुमान?',
    question5: 'जैविक कीट नियंत्रण विधियां?',
    question6: 'किसानों के लिए सरकारी योजनाएं?',
    clouds: 'बादल',
    sunny: 'धूप',
    rainy: 'बरसात',
    // Weather Conditions
    weatherClouds: 'बादल',
    weatherClear: 'साफ',
    weatherRain: 'बारिश',
    weatherDrizzle: 'बूंदाबांदी',
    weatherThunderstorm: 'आंधी-तूफान',
    weatherSnow: 'बर्फ',
    weatherMist: 'धुंध',
    weatherHaze: 'धुंधलापन',
    weatherFog: 'घना कोहरा',
    weatherDust: 'धूल',
    weatherSmoke: 'धुआं',

    // Image Analysis
    uploadCropImagesAnalysis: 'AI संचालित रोग पहचान और विश्लेषण के लिए फसल की तस्वीरें अपलोड करें',
    dragDropImage: 'यहाँ एक छवि खींचें और छोड़ें',
    or: 'या',
    browseFiles: 'फाइलें ब्राउज़ करें',
    analyzeImage: 'छवि विश्लेषण करें',
    analyzing: 'विश्लेषण हो रहा है...',
    analysisResults: 'विश्लेषण परिणाम',
    diseaseStatus: 'रोग स्थिति',
    detected: 'पता चला',
    noDisease: 'कोई रोग नहीं मिला',
    confidence: 'विश्वास',
    severity: 'गंभीरता',
    affectedArea: 'प्रभावित क्षेत्र',
    recommendations: 'सिफारिशें',
    treatment: 'उपचार',
    prevention: 'रोकथाम',
    uploadNewImage: 'नई छवि अपलोड करें',
    additionalInformation: 'अतिरिक्त जानकारी',
    cropTypeOptional: 'फसल का प्रकार (वैकल्पिक)',
    cropTypePlaceholder: 'उदा., धान, नारियल, मूंगफली',
    symptomsNotesOptional: 'लक्षण/नोट्स (वैकल्पिक)',
    symptomsPlaceholder: 'आपने जो लक्षण देखे हैं उनका वर्णन करें...',
    analyzingImage: 'छवि का विश्लेषण हो रहा है...',
    readyToAnalyze: 'विश्लेषण के लिए तैयार',
    readyToAnalyzeDesc: 'अपनी फसल की स्पष्ट छवि अपलोड करें और AI संचालित रोग पहचान परिणाम प्राप्त करने के लिए विश्लेषण पर क्लिक करें।',
    tipsForBetterAnalysis: 'बेहतर विश्लेषण के लिए सुझाव',
    clearImages: 'स्पष्ट छवियां',
    clearImagesDesc: 'प्रभावित क्षेत्रों को स्पष्ट रूप से दिखाने वाली अच्छी रोशनी वाली तस्वीरें लें',
    closeUpShots: 'क्लोज-अप शॉट्स',
    closeUpShotsDesc: 'धब्बे, रंग परिवर्तन या क्षति जैसे विशिष्ट लक्षणों पर ध्यान दें',
    additionalInfo: 'अतिरिक्त जानकारी',
    additionalInfoDesc: 'अधिक सटीक परिणामों के लिए फसल का प्रकार और लक्षण विवरण प्रदान करें',
    changeImage: 'छवि बदलें',
    confidenceScore: 'विश्वास स्कोर',
    healthStatus: 'स्वास्थ्य स्थिति',
    recommendedTreatment: 'अनुशंसित उपचार',
    preventionTips: 'रोकथाम के सुझाव',
    saveReport: 'रिपोर्ट सहेजें',
    shareResults: 'परिणाम साझा करें',

    // Crop Advisory
    farmDetails: 'खेत विवरण',
    locationDistrict: 'स्थान/जिला',
    locationPlaceholder: 'उदा., कोयंबटूर, त्रिशूर',
    selectSoilType: 'मिट्टी का प्रकार चुनें',
    clayey: 'चिकनी मिट्टी',
    sandy: 'रेतीली',
    loamy: 'दोमट',
    redSoil: 'लाल मिट्टी',
    blackSoil: 'काली मिट्टी',
    laterite: 'लेटराइट',
    alluvial: 'जलोढ़ मिट्टी',
    farmSizePlaceholder: 'उदा., 2 एकड़',
    preferredSeason: 'पसंदीदा सीजन',
    selectSeason: 'सीजन चुनें',
    kharif: 'खरीफ (जून-अक्टूबर)',
    rabi: 'रबी (अक्टूबर-मार्च)',
    summer: 'गर्मी (मार्च-जून)',
    perennialCrops: 'बहुवर्षीय फसलें',
    waterSource: 'जल स्रोत',
    selectWaterSource: 'जल स्रोत चुनें',
    rainFed: 'वर्षा आधारित',
    irrigationSource: 'सिंचाई',
    borewell: 'बोरवेल',
    canal: 'नहर',
    river: 'नदी',
    analyzingCrops: 'विश्लेषण हो रहा है...',
    currentConditions: 'वर्तमान स्थितियां',
    rainfallLabel: 'वर्षा:',
    temperatureLabel: 'तापमान:',
    humidityLabel: 'आर्द्रता:',
    expected: 'अपेक्षित',
    cropRecommendations: 'फसल सिफारिशें',
    cropsFound: 'फसलें मिलीं',
    suitability: 'उपयुक्तता',
    soilTypes: 'मिट्टी के प्रकार',
    demand: 'मांग',
    risk: 'जोखिम',
    advantages: 'फायदे',
    challenges: 'चुनौतियां',
    readyForRecommendations: 'सिफारिशों के लिए तैयार',
    readyForRecommendationsDesc: 'बाईं ओर अपने खेत का विवरण भरें और व्यक्तिगत फसल सुझाव प्राप्त करने के लिए "सिफारिशें प्राप्त करें" पर क्लिक करें।',

    // Weather
    realTimeWeatherData: 'बेहतर खेती निर्णयों के लिए रीयल-टाइम मौसम डेटा और कृषि पूर्वानुमान',
    getWeather: 'मौसम प्राप्त करें',
    currentWeather: 'वर्तमान मौसम',
    windSpeed: 'हवा की गति',
    visibility: 'दृश्यता',
    pressure: 'दबाव',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    forecast: 'पूर्वानुमान',
    sevenDayForecast: '7-दिन का पूर्वानुमान',
    today: 'आज',
    tomorrow: 'कल',
    viewFullForecast: 'पूर्ण पूर्वानुमान देखें',
    todaysTip: 'आज की टिप',
    learnMore: 'और जानें',

    // Crop Advisory
    getCropAdvisoryRecommendations: 'अपनी परिस्थितियों के आधार पर फसल सलाह और व्यक्तिगत सिफारिशें प्राप्त करें',
    selectCropType: 'फसल प्रकार चुनें',
    soilType: 'मिट्टी का प्रकार',
    season: 'मौसम',
    getRecommendations: 'सिफारिशें प्राप्त करें',
    fetching: 'प्राप्त हो रहा है...',
    advisory: 'सलाह',
    bestPractices: 'सर्वोत्तम अभ्यास',
    expectedYield: 'अपेक्षित उपज',
    waterRequirements: 'पानी की आवश्यकताएं',
    fertilizerNeeds: 'उर्वरक आवश्यकताएं',
    commonPests: 'सामान्य कीट',
    harvestTime: 'कटाई का समय',

    // Soil Health
    soilTestingAndHealth: 'इष्टतम फसल वृद्धि के लिए मिट्टी परीक्षण और स्वास्थ्य निगरानी',
    requestSoilTest: 'मिट्टी परीक्षण अनुरोध करें',
    viewReports: 'रिपोर्ट देखें',
    soilNutrients: 'मिट्टी पोषक तत्व',
    nitrogen: 'नाइट्रोजन',
    phosphorus: 'फास्फोरस',
    potassium: 'पोटेशियम',
    organic: 'जैविक',
    phLevel: 'pH स्तर',
    optimal: 'इष्टतम',

    // Government Schemes
    governmentSchemesForFarmers: 'किसानों के लिए उपलब्ध सरकारी योजनाओं को ब्राउज़ करें और आवेदन करें',
    availableSchemes: 'उपलब्ध योजनाएं',
    eligibility: 'पात्रता',
    benefits: 'लाभ',
    howToApply: 'आवेदन कैसे करें',
    applyNow: 'अभी आवेदन करें',
    deadline: 'अंतिम तिथि',

    // Disease Management
    identifyManageDiseases: 'विशेषज्ञ मार्गदर्शन के साथ फसल रोगों की पहचान और प्रबंधन करें',
    commonDiseases: 'सामान्य रोग',
    symptoms: 'लक्षण',
    causes: 'कारण',
    control: 'नियंत्रण',
    organicSolutions: 'जैविक समाधान',
    chemicalTreatment: 'रासायनिक उपचार',

    // Cultivation Guide
    stepByStepGuide: 'विभिन्न फसलों के लिए चरण-दर-चरण खेती गाइड',
    selectCrop: 'फसल चुनें',
    landPreparation: 'भूमि तैयारी',
    sowing: 'बुवाई',
    irrigation: 'सिंचाई',
    weeding: 'निराई',
    harvesting: 'कटाई',
    postHarvest: 'कटाई के बाद',
    duration: 'अवधि',
    investment: 'निवेश',

    // Soil Health Page
    soilHealthDesc: 'बेहतर फसल उपज के लिए अपनी मिट्टी की संरचना का विश्लेषण करें और व्यक्तिगत सिफारिशें प्राप्त करें',
    soilTestData: 'मिट्टी परीक्षण डेटा',
    sampleLocation: 'नमूना स्थान',
    sampleLocationPlaceholder: 'उदा., फार्म ब्लॉक A, कोयंबटूर',
    sampleDate: 'नमूना तारीख',
    depthCm: 'गहराई (सेमी)',
    nutrientLevelsOptional: 'पोषक तत्व स्तर (वैकल्पिक)',
    organicMatterPercent: 'कार्बनिक पदार्थ (%)',
    nitrogenKgHa: 'नाइट्रोजन (किलो/हेक्टेयर)',
    phosphorusKgHa: 'फास्फोरस (किलो/हेक्टेयर)',
    potassiumKgHa: 'पोटेशियम (किलो/हेक्टेयर)',
    cropPlanned: 'नियोजित फसल',
    selectCropPlaceholder: 'फसल चुनें',
    ricePaddy: 'चावल/धान',
    coconut: 'नारियल',
    groundnut: 'मूंगफली',
    banana: 'केला',
    pepper: 'काली मिर्च',
    vegetables: 'सब्जियां',
    millets: 'बाजरा',
    additionalNotes: 'अतिरिक्त नोट्स',
    additionalNotesPlaceholder: 'मिट्टी की स्थिति के बारे में कोई अवलोकन...',
    analyzingSoil: 'विश्लेषण हो रहा है...',
    analyzeSoil: 'मिट्टी का विश्लेषण करें',
    overallSoilHealthScore: 'समग्र मिट्टी स्वास्थ्य स्कोर',
    excellent: 'उत्कृष्ट',
    good: 'अच्छा',
    needsImprovement: 'सुधार आवश्यक',
    organicMatter: 'कार्बनिक पदार्थ',
    nutrientRecommendations: 'पोषक तत्व सिफारिशें',
    recommendedProducts: 'अनुशंसित उत्पाद:',
    suitableCrops: 'उपयुक्त फसलें',
    improvementTips: 'सुधार के सुझाव',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    readyToAnalyzeSoil: 'विश्लेषण के लिए तैयार',
    readyToAnalyzeSoilDesc: 'बाईं ओर अपना मिट्टी परीक्षण डेटा दर्ज करें या मिट्टी सुधार के लिए व्यक्तिगत सिफारिशें प्राप्त करने के लिए लैब रिपोर्ट अपलोड करें।',
    dontHaveTestData: 'परीक्षण डेटा नहीं है?',
    generalRecommendationsNote: 'केवल अपना स्थान दर्ज करके सामान्य सिफारिशें प्राप्त कर सकते हैं!',
    missingInformation: 'जानकारी गायब है',
    enterSampleLocation: 'कृपया कम से कम नमूना स्थान दर्ज करें।',
    soilAnalysisComplete: 'विश्लेषण पूर्ण',
    soilAnalysisSuccess: 'मिट्टी स्वास्थ्य विश्लेषण सफलतापूर्वक तैयार किया गया।',

    // Disease Management Page
    diseaseManagementDesc: 'विशेषज्ञ मार्गदर्शन के साथ फसल रोगों की पहचान करें, उपचार करें और रोकें',
    searchDiseasesPlaceholder: 'रोग, लक्षण या फसलें खोजें...',
    highRisk: 'उच्च जोखिम',
    mediumRisk: 'मध्यम जोखिम',
    lowRisk: 'कम जोखिम',
    riceBlast: 'चावल ब्लास्ट',
    riceBlastSymptoms: 'पत्तियों पर पीले घेरों के साथ भूरे धब्बे',
    riceBlastTreatment: 'ट्राइसाइक्लाज़ोल कवकनाशी लगाएं',
    riceBlastPrevention: 'प्रतिरोधी किस्मों का उपयोग करें, उचित जल निकासी',
    coconutRootWilt: 'नारियल जड़ सड़न',
    coconutRootWiltSymptoms: 'बाहरी पत्तियों का पीला होना, नारियल उत्पादन में कमी',
    coconutRootWiltTreatment: 'संतुलित उर्वरक के साथ जड़ पोषण',
    coconutRootWiltPrevention: 'उचित जल निकासी, जैविक पदार्थ जोड़ना',

    // Cultivation Guide Page
    cultivationGuideDesc: 'तमिलनाडु और केरल में प्रमुख फसलों के लिए चरण-दर-चरण खेती गाइड',
    paddy: 'धान',
    paddyRice: 'धान (चावल)',
    coconutCrop: 'नारियल',
    cultivationGuideTitle: 'खेती गाइड',
    landPreparationDesc: 'खेत की जुताई करें, जमीन समतल करें, नर्सरी बेड तैयार करें',
    landPreparationDuration: '15 दिन',
    sowingTransplanting: 'बुवाई/रोपाई',
    sowingTransplantingDesc: 'नर्सरी में बीज बोएं, 30 दिन पुरानी पौध की रोपाई करें',
    sowingTransplantingDuration: '30-35 दिन',
    vegetativeGrowth: 'वानस्पतिक विकास',
    vegetativeGrowthDesc: 'उर्वरक लगाएं, पानी का स्तर बनाए रखें, खरपतवार नियंत्रण',
    vegetativeGrowthDuration: '40-50 दिन',
    reproductivePhase: 'प्रजनन चरण',
    reproductivePhaseDesc: 'बाली निकलना, फूल आना, दाना बनना',
    reproductivePhaseDuration: '30-35 दिन',
    maturation: 'परिपक्वता',
    maturationDesc: 'दाना भरना, कटाई से पहले खेत सुखाना',
    maturationDuration: '30 दिन',
    siteSelection: 'स्थान चयन',
    siteSelectionDesc: 'अच्छी जल निकासी वाले तटीय या अंतर्देशीय क्षेत्रों का चयन करें',
    initial: 'प्रारंभिक',
    planting: 'रोपण',
    plantingDesc: 'उचित दूरी के साथ गुणवत्ता वाले पौधे लगाएं (7.5 मी x 7.5 मी)',
    oneMonth: '1 महीना',
    youngPalmCare: 'युवा पाम देखभाल',
    youngPalmCareDesc: 'नियमित सिंचाई, उर्वरण, कीट प्रबंधन',
    threeToFiveYears: '3-5 साल',
    bearingStage: 'फलने की अवस्था',
    bearingStageDesc: 'हर 45 दिन पर नियमित कटाई, निरंतर देखभाल',
    fivePlusYears: '5+ साल',
    maintenance: 'रखरखाव',
    maintenanceDesc: 'छंटाई, उर्वरण, रोग निगरानी',
    ongoing: 'चालू',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};